-- country group and code
insert into type_group(group_cd,type_cd_prefix,group_description,created_by,creation_dt,last_updated_by,last_update_dt) values ('country_cd','cc_','group code for country codes',1,curdate(),1,curdate());

insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_ad','country_cd','Andorra','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_ae','country_cd','United Arab Emirates','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_af','country_cd','Afghanistan','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_ag','country_cd','Antigua And Barbuda','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_ai','country_cd','Anguilla','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_al','country_cd','Albania','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_am','country_cd','Armenia','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_ao','country_cd','Angola','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_aq','country_cd','Antarctica','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_ar','country_cd','Argentina','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_as','country_cd','American Samoa','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_at','country_cd','Austria','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_au','country_cd','Australia','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_aw','country_cd','Aruba','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_ax','country_cd','Åland Islands','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_az','country_cd','Azerbaijan','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_ba','country_cd','Bosnia And Herzegovina','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_bb','country_cd','Barbados','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_bd','country_cd','Bangladesh','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_be','country_cd','Belgium','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_bf','country_cd','Burkina Faso','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_bg','country_cd','Bulgaria','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_bh','country_cd','Bahrain','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_bi','country_cd','Burundi','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_bj','country_cd','Benin','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_bl','country_cd','Saint Barthélemy','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_bm','country_cd','Bermuda','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_bn','country_cd','Brunei Darussalam','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_bo','country_cd','Bolivia','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_bq','country_cd','Caribbean Netherlands','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_br','country_cd','Brazil','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_bs','country_cd','Bahamas','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_bt','country_cd','Bhutan','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_bv','country_cd','Bouvet Island','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_bw','country_cd','Botswana','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_by','country_cd','Belarus','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_bz','country_cd','Belize','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_ca','country_cd','Canada','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_cc','country_cd','Cocos (keeling) Islands','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_cd','country_cd','Congo','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_cf','country_cd','Central African Republic','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_cg','country_cd','Congo','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_ch','country_cd','Switzerland','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_ci','country_cd',"Cote D'ivoire",'tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_ck','country_cd','Cook Islands','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_cl','country_cd','Chile','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_cm','country_cd','Cameroon','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_cn','country_cd','China','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_co','country_cd','Colombia','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_cr','country_cd','Costa Rica','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_cu','country_cd','Cuba','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_cv','country_cd','Cape Verde','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_cw','country_cd','Curaçao','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_cx','country_cd','Christmas Island','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_cy','country_cd','Cyprus','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_cz','country_cd','Czech Republic','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_de','country_cd','Germany','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_dj','country_cd','Djibouti','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_dk','country_cd','Denmark','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_dm','country_cd','Dominica','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_do','country_cd','Dominican Republic','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_dz','country_cd','Algeria','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_ec','country_cd','Ecuador','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_ee','country_cd','Estonia','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_eg','country_cd','Egypt','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_eh','country_cd','Western Sahara','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_er','country_cd','Eritrea','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_es','country_cd','Spain','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_et','country_cd','Ethiopia','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_fi','country_cd','Finland','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_fj','country_cd','Fiji','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_fk','country_cd','Falkland Islands','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_fm','country_cd','Micronesia','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_fo','country_cd','Faroe Islands','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_fr','country_cd','France','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_ga','country_cd','Gabon','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_gb','country_cd','United Kingdom','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_gd','country_cd','Grenada','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_ge','country_cd','Georgia','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_gf','country_cd','French Guiana','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_gg','country_cd','Guernsey','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_gh','country_cd','Ghana','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_gi','country_cd','Gibraltar','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_gl','country_cd','Greenland','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_gm','country_cd','Gambia','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_gn','country_cd','Guinea','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_gp','country_cd','Guadeloupe','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_gq','country_cd','Equatorial Guinea','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_gr','country_cd','Greece','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_gs','country_cd','South Georgia And The South Sandwich Islands','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_gt','country_cd','Guatemala','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_gu','country_cd','Guam','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_gw','country_cd','Guinea-bissau','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_gy','country_cd','Guyana','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_hk','country_cd','Hong Kong','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_hm','country_cd','Heard And Mcdonald Islands','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_hn','country_cd','Honduras','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_hr','country_cd','Croatia','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_ht','country_cd','Haiti','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_hu','country_cd','Hungary','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_id','country_cd','Indonesia','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_ie','country_cd','Ireland','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_il','country_cd','Israel','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_im','country_cd','Isle Of Man','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_in','country_cd','India','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_io','country_cd','British Indian Ocean Territory','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_iq','country_cd','Iraq','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_ir','country_cd','Iran','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_is','country_cd','Iceland','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_it','country_cd','Italy','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_je','country_cd','Jersey','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_jm','country_cd','Jamaica','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_jo','country_cd','Jordan','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_jp','country_cd','Japan','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_ke','country_cd','Kenya','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_kg','country_cd','Kyrgyzstan','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_kh','country_cd','Cambodia','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_ki','country_cd','Kiribati','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_km','country_cd','Comoros','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_kn','country_cd','Saint Kitts And Nevis','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_kp','country_cd','North Korea','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_kr','country_cd','South Korea','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_kw','country_cd','Kuwait','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_ky','country_cd','Cayman Islands','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_kz','country_cd','Kazakhstan','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_la','country_cd',"Lao People's Democratic Republic",'tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_lb','country_cd','Lebanon','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_lc','country_cd','Saint Lucia','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_li','country_cd','Liechtenstein','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_lk','country_cd','Sri Lanka','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_lr','country_cd','Liberia','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_ls','country_cd','Lesotho','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_lt','country_cd','Lithuania','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_lu','country_cd','Luxembourg','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_lv','country_cd','Latvia','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_ly','country_cd','Libya','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_ma','country_cd','Morocco','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_mc','country_cd','Monaco','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_md','country_cd','Moldova','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_me','country_cd','Montenegro','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_mf','country_cd','Saint-martin (france)','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_mg','country_cd','Madagascar','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_mh','country_cd','Marshall Islands','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_mk','country_cd','Macedonia','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_ml','country_cd','Mali','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_mm','country_cd','Myanmar','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_mn','country_cd','Mongolia','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_mo','country_cd','Macau','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_mp','country_cd','Northern Mariana Islands','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_mq','country_cd','Martinique','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_mr','country_cd','Mauritania','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_ms','country_cd','Montserrat','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_mt','country_cd','Malta','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_mu','country_cd','Mauritius','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_mv','country_cd','Maldives','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_mw','country_cd','Malawi','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_mx','country_cd','Mexico','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_my','country_cd','Malaysia','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_mz','country_cd','Mozambique','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_na','country_cd','Namibia','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_nc','country_cd','New Caledonia','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_ne','country_cd','Niger','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_nf','country_cd','Norfolk Island','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_ng','country_cd','Nigeria','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_ni','country_cd','Nicaragua','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_nl','country_cd','The Netherlands','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_no','country_cd','Norway','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_np','country_cd','Nepal','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_nr','country_cd','Nauru','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_nu','country_cd','Niue','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_nz','country_cd','New Zealand','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_om','country_cd','Oman','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_pa','country_cd','Panama','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_pe','country_cd','Peru','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_pf','country_cd','French Polynesia','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_pg','country_cd','Papua New Guinea','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_ph','country_cd','Philippines','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_pk','country_cd','Pakistan','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_pl','country_cd','Poland','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_pm','country_cd','St. Pierre And Miquelon','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_pn','country_cd','Pitcairn','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_pr','country_cd','Puerto Rico','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_ps','country_cd','Palestinian Territory','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_pt','country_cd','Portugal','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_pw','country_cd','Palau','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_py','country_cd','Paraguay','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_qa','country_cd','Qatar','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_re','country_cd','Reunion','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_ro','country_cd','Romania','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_rs','country_cd','Serbia','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_ru','country_cd','Russian Federation','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_rw','country_cd','Rwanda','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_sa','country_cd','Saudi Arabia','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_sb','country_cd','Solomon Islands','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_sc','country_cd','Seychelles','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_sd','country_cd','Sudan','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_se','country_cd','Sweden','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_sg','country_cd','Singapore','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_sh','country_cd','Saint Helena','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_si','country_cd','Slovenia','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_sj','country_cd','Svalbard And Jan Mayen Islands','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_sk','country_cd','Slovakia (slovak Republic)','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_sl','country_cd','Sierra Leone','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_sm','country_cd','San Marino','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_sn','country_cd','Senegal','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_so','country_cd','Somalia','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_sr','country_cd','Suriname','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_ss','country_cd','South Sudan','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_st','country_cd','Sao Tome And Principe','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_sv','country_cd','El Salvador','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_sx','country_cd','Saint-martin (pays-bas)','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_sy','country_cd','Syria','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_sz','country_cd','Swaziland','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_tc','country_cd','Turks And Caicos Islands','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_td','country_cd','Chad','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_tf','country_cd','French Southern Territories','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_tg','country_cd','Togo','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_th','country_cd','Thailand','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_tj','country_cd','Tajikistan','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_tk','country_cd','Tokelau','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_tl','country_cd','Timor-leste','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_tm','country_cd','Turkmenistan','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_tn','country_cd','Tunisia','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_to','country_cd','Tonga','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_tr','country_cd','Turkey','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_tt','country_cd','Trinidad And Tobago','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_tv','country_cd','Tuvalu','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_tw','country_cd','Taiwan','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_tz','country_cd','Tanzania','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_ua','country_cd','Ukraine','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_ug','country_cd','Uganda','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_um','country_cd','United States Minor Outlying Islands','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_us','country_cd','United States','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_uy','country_cd','Uruguay','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_uz','country_cd','Uzbekistan','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_va','country_cd','Vatican','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_vc','country_cd','Saint Vincent And The Grenadines','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_ve','country_cd','Venezuela','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_vg','country_cd','Virgin Islands (british)','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_vi','country_cd','Virgin Islands (u.s.)','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_vn','country_cd','Vietnam','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_vu','country_cd','Vanuatu','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_wf','country_cd','Wallis And Futuna Islands','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_ws','country_cd','Samoa','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_ye','country_cd','Yemen','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_yt','country_cd','Mayotte','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_za','country_cd','South Africa','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_zm','country_cd','Zambia','tcs_act',1,curdate(),1,curdate());
insert into type_table(type_cd,group_cd,type_description,status_cd,created_by,creation_dt,last_updated_by,last_update_dt) values ('cc_zw','country_cd','Zimbabwe','tcs_act',1,curdate(),1,curdate());
