package com.anucana.constants;

public interface IBusinessConstants {

	String PAYMENT_RESPONSE_STATUS_SUCCESS = "success";
	String PAYMENT_RESPONSE_STATUS_PENDING = "pending";
	String PAYMENT_RESPONSE_STATUS_FAILURE = "failure";
	
	String PAYMENT_TRANSACTION_MODE_CREDIT_CARD = "CC";
	String PAYMENT_TRANSACTION_MODE_NET_BANKING = "NB";
	String PAYMENT_TRANSACTION_MODE_CHEQUE = "CD";
	String PAYMENT_TRANSACTION_MODE_DEMAND_DRAFT = "DD";
	String PAYMENT_TRANSACTION_MODE_CASH_PICKUP = "CO";
	
}
