insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744104,'Andaman And nicobar islands','South Andaman','Aberdeen bazar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744107,'Andaman And nicobar islands','South Andaman','Bambooflat','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744108,'Andaman And nicobar islands','South Andaman','Beachdera','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744105,'Andaman And nicobar islands','South Andaman','Beodnabad','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744105,'Andaman And nicobar islands','South Andaman','Bimbiton','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744103,'Andaman And nicobar islands','South Andaman','Brijgunj','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744105,'Andaman And nicobar islands','South Andaman','Calicut','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744103,'Andaman And nicobar islands','South Andaman','Chouldari','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744206,'Andaman And nicobar islands','South Andaman','Dundas Point','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744105,'Andaman And nicobar islands','South Andaman','Garacharama','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744103,'Andaman And nicobar islands','South Andaman','Guptapara','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744102,'Andaman And nicobar islands','South Andaman','Haddo','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744211,'Andaman And nicobar islands','South Andaman','Havelock','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744211,'Andaman And nicobar islands','South Andaman','Havelock bazar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744109,'Andaman And nicobar islands','South Andaman','Herbertabad','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744110,'Andaman And nicobar islands','South Andaman','Humferygunj','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744207,'Andaman And nicobar islands','South Andaman','Hut bay','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744206,'Andaman And nicobar islands','South Andaman','Jirkatong','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744103,'Andaman And nicobar islands','South Andaman','Junglighat','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744206,'Andaman And nicobar islands','South Andaman','Kalatong','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744206,'Andaman And nicobar islands','South Andaman','Mathura','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744206,'Andaman And nicobar islands','South Andaman','Miletilak','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744104,'Andaman And nicobar islands','South Andaman','Neil Island','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744207,'Andaman And nicobar islands','South Andaman','Netajinagar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744103,'Andaman And nicobar islands','South Andaman','Ograbanj','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744211,'Andaman And nicobar islands','South Andaman','Peal Island','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744101,'Andaman And nicobar islands','South Andaman','Port Blair','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744207,'Andaman And nicobar islands','South Andaman','Ramakrishnapur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744111,'Andaman And nicobar islands','South Andaman','Rubber Research station','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744105,'Andaman And nicobar islands','South Andaman','Rutland','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744103,'Andaman And nicobar islands','South Andaman','School Line','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744106,'Andaman And nicobar islands','South Andaman','Shadipur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744206,'Andaman And nicobar islands','South Andaman','Shoalbay','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744105,'Andaman And nicobar islands','South Andaman','Sippighat','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744104,'Andaman And nicobar islands','South Andaman','Sitapur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744107,'Andaman And nicobar islands','South Andaman','Stewertgunj','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744211,'Andaman And nicobar islands','South Andaman','Strait island','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744103,'Andaman And nicobar islands','South Andaman','Tushnabad','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744207,'Andaman And nicobar islands','South Andaman','Vivekandapur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744103,'Andaman And nicobar islands','South Andaman','Wandoor','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744206,'Andaman And nicobar islands','South Andaman','Wimberlygunj','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744202,'Andaman And nicobar islands','North And middle andaman','Aerial Bay','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744208,'Andaman And nicobar islands','North And middle andaman','Bakultala','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744201,'Andaman And nicobar islands','North And middle andaman','Betapur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744202,'Andaman And nicobar islands','North And middle andaman','Diglipur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744202,'Andaman And nicobar islands','North And middle andaman','Hathilevel','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744209,'Andaman And nicobar islands','North And middle andaman','Kadamtala','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744202,'Andaman And nicobar islands','North And middle andaman','Kalighat','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744210,'Andaman And nicobar islands','North And middle andaman','Kanchangarh','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744205,'Andaman And nicobar islands','North And middle andaman','Kaushalyanagar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744202,'Andaman And nicobar islands','North And middle andaman','Kishorinagar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744202,'Andaman And nicobar islands','North And middle andaman','Laxmipur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744203,'Andaman And nicobar islands','North And middle andaman','Long Island','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744204,'Andaman And nicobar islands','North And middle andaman','Mayabander','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744202,'Andaman And nicobar islands','North And middle andaman','Navagram','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744201,'Andaman And nicobar islands','North And middle andaman','Nimbudera','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744205,'Andaman And nicobar islands','North And middle andaman','Nimbutala','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744210,'Andaman And nicobar islands','North And middle andaman','Oralkatcha','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744205,'Andaman And nicobar islands','North And middle andaman','Panchawati','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744205,'Andaman And nicobar islands','North And middle andaman','Parnasala','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744202,'Andaman And nicobar islands','North And middle andaman','Pashimsagar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744201,'Andaman And nicobar islands','North And middle andaman','Pitchernalla','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744204,'Andaman And nicobar islands','North And middle andaman','Pudumadurai','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744202,'Andaman And nicobar islands','North And middle andaman','Ramnagar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744204,'Andaman And nicobar islands','North And middle andaman','Rampur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744205,'Andaman And nicobar islands','North And middle andaman','Rangat','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744205,'Andaman And nicobar islands','North And middle andaman','Sabari','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744210,'Andaman And nicobar islands','North And middle andaman','Sankarnalla','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744202,'Andaman And nicobar islands','North And middle andaman','Sitanagar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744202,'Andaman And nicobar islands','North And middle andaman','Smith island','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744202,'Andaman And nicobar islands','North And middle andaman','Swarajgram','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744201,'Andaman And nicobar islands','North And middle andaman','Swdeshnagar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744204,'Andaman And nicobar islands','North And middle andaman','Tugapur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744209,'Andaman And nicobar islands','North And middle andaman','Uttara','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744204,'Andaman And nicobar islands','North And middle andaman','Weby','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744302,'Andaman And nicobar islands','Nicobar','Campbelbay','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744301,'Andaman And nicobar islands','Nicobar','Carnicobar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744303,'Andaman And nicobar islands','Nicobar','Champin','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744303,'Andaman And nicobar islands','Nicobar','Chowra','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744302,'Andaman And nicobar islands','Nicobar','Gandhinagar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744301,'Andaman And nicobar islands','Nicobar','Kakana','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744304,'Andaman And nicobar islands','Nicobar','Kapanga','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744302,'Andaman And nicobar islands','Nicobar','Kondul Island','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744301,'Andaman And nicobar islands','Nicobar','Lapathy','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744302,'Andaman And nicobar islands','Nicobar','Little Nicobar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744304,'Andaman And nicobar islands','Nicobar','Mildera','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744301,'Andaman And nicobar islands','Nicobar','Mus','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744303,'Andaman And nicobar islands','Nicobar','Nancowrie','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744304,'Andaman And nicobar islands','Nicobar','Nehrugram','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744302,'Andaman And nicobar islands','Nicobar','Pilomilo Island','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744301,'Andaman And nicobar islands','Nicobar','Sawai','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744302,'Andaman And nicobar islands','Nicobar','Shabnamnagar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744303,'Andaman And nicobar islands','Nicobar','Teressa','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,744303,'Andaman And nicobar islands','Nicobar','Trinket','cc_in');
