insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792056,'Arunachal Pradesh','Changlang','Bordumsa','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792120,'Arunachal Pradesh','Changlang','Bubang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792120,'Arunachal Pradesh','Changlang','Changlang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792122,'Arunachal Pradesh','Changlang','Chopelling','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792122,'Arunachal Pradesh','Changlang','Deban','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792122,'Arunachal Pradesh','Changlang','Dharampur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792055,'Arunachal Pradesh','Changlang','Gandhigram','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792121,'Arunachal Pradesh','Changlang','Jairampur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792122,'Arunachal Pradesh','Changlang','Kharsang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792120,'Arunachal Pradesh','Changlang','Khemiyong','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792056,'Arunachal Pradesh','Changlang','Kherem Bisa','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792122,'Arunachal Pradesh','Changlang','Kutum Basti','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792056,'Arunachal Pradesh','Changlang','Lallung','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792122,'Arunachal Pradesh','Changlang','Manabhum','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792121,'Arunachal Pradesh','Changlang','Manmao','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792122,'Arunachal Pradesh','Changlang','Miao','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792122,'Arunachal Pradesh','Changlang','Namchik','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792120,'Arunachal Pradesh','Changlang','Namdang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792122,'Arunachal Pradesh','Changlang','Namphai','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792120,'Arunachal Pradesh','Changlang','Namtok','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792056,'Arunachal Pradesh','Changlang','New Mohang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792056,'Arunachal Pradesh','Changlang','Rajanagar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792120,'Arunachal Pradesh','Changlang','Rangfrah Covt college','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792120,'Arunachal Pradesh','Changlang','Ranglum','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792055,'Arunachal Pradesh','Changlang','Two-hat','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792055,'Arunachal Pradesh','Changlang','Vijoynagar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792056,'Arunachal Pradesh','Changlang','Vijoypur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792120,'Arunachal Pradesh','Changlang','Yangkang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791118,'Arunachal Pradesh','Kurung Kumey','Chambang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791118,'Arunachal Pradesh','Kurung Kumey','Damin','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791118,'Arunachal Pradesh','Kurung Kumey','Hiya','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791118,'Arunachal Pradesh','Kurung Kumey','Koloriang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791118,'Arunachal Pradesh','Kurung Kumey','Nyapin','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791118,'Arunachal Pradesh','Kurung Kumey','Palin','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791118,'Arunachal Pradesh','Kurung Kumey','Sangram','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791118,'Arunachal Pradesh','Kurung Kumey','Sarli','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791118,'Arunachal Pradesh','Kurung Kumey','Tali','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,790102,'Arunachal Pradesh','East Kameng','Bameng','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,790102,'Arunachal Pradesh','East Kameng','Bana','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,790102,'Arunachal Pradesh','East Kameng','Chyangtajo','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,790102,'Arunachal Pradesh','East Kameng','Khenewa','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,790102,'Arunachal Pradesh','East Kameng','Lada','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,790102,'Arunachal Pradesh','East Kameng','P.Kessang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,790102,'Arunachal Pradesh','East Kameng','Palizi','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,790102,'Arunachal Pradesh','East Kameng','Pipu-dipu','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,790103,'Arunachal Pradesh','East Kameng','Seijosa','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,790102,'Arunachal Pradesh','East Kameng','Seppa','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,790102,'Arunachal Pradesh','East Kameng','Thrizino','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,790102,'Arunachal Pradesh','East Kameng','Veo','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,790002,'Arunachal Pradesh','West Kameng','Balemu','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,790114,'Arunachal Pradesh','West Kameng','Bhalukpong','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,790001,'Arunachal Pradesh','West Kameng','Bomdila','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,790116,'Arunachal Pradesh','West Kameng','Dahung','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,790116,'Arunachal Pradesh','West Kameng','Dedza','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,790101,'Arunachal Pradesh','West Kameng','Dirang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,790101,'Arunachal Pradesh','West Kameng','Dirang Basti','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,790002,'Arunachal Pradesh','West Kameng','Kalaktang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,790114,'Arunachal Pradesh','West Kameng','Khellong','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,790101,'Arunachal Pradesh','West Kameng','Lish','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,790101,'Arunachal Pradesh','West Kameng','Munna Camp','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,790001,'Arunachal Pradesh','West Kameng','Nafra','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,790003,'Arunachal Pradesh','West Kameng','Rupa','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,790001,'Arunachal Pradesh','West Kameng','Salari','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,790101,'Arunachal Pradesh','West Kameng','Sangti','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,790101,'Arunachal Pradesh','West Kameng','Senge','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,790003,'Arunachal Pradesh','West Kameng','Shergaon','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,790116,'Arunachal Pradesh','West Kameng','Singchung','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,790116,'Arunachal Pradesh','West Kameng','Tenga Market','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,790002,'Arunachal Pradesh','West Kameng','Tenzingaon','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,790114,'Arunachal Pradesh','West Kameng','Tippi','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,786630,'Arunachal Pradesh','Tirap','Borduria','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,786630,'Arunachal Pradesh','Tirap','Dadam','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,786629,'Arunachal Pradesh','Tirap','Deomali','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,786629,'Arunachal Pradesh','Tirap','Hukanjuri','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,786631,'Arunachal Pradesh','Tirap','K/nokno','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,786630,'Arunachal Pradesh','Tirap','Kaimai','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,786630,'Arunachal Pradesh','Tirap','Kanubari','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,786630,'Arunachal Pradesh','Tirap','Kapu','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,786630,'Arunachal Pradesh','Tirap','Khela','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,786630,'Arunachal Pradesh','Tirap','Kheti','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,786630,'Arunachal Pradesh','Tirap','Khonsa','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,786630,'Arunachal Pradesh','Tirap','Khonsa Basti','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,786631,'Arunachal Pradesh','Tirap','Khotnu','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,786630,'Arunachal Pradesh','Tirap','Lazu','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,786631,'Arunachal Pradesh','Tirap','Longding','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,786631,'Arunachal Pradesh','Tirap','Longfong','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,786631,'Arunachal Pradesh','Tirap','Minthong','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792123,'Arunachal Pradesh','Tirap','Nampong','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,786629,'Arunachal Pradesh','Tirap','Namsang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,786629,'Arunachal Pradesh','Tirap','Namsang Mukh','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,786629,'Arunachal Pradesh','Tirap','Narottam Nagar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,786631,'Arunachal Pradesh','Tirap','Nginu','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,786631,'Arunachal Pradesh','Tirap','Niausa','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,786631,'Arunachal Pradesh','Tirap','Panchou','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,786631,'Arunachal Pradesh','Tirap','Senewa','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,786629,'Arunachal Pradesh','Tirap','Soha','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,786630,'Arunachal Pradesh','Tirap','Thinsa','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,786631,'Arunachal Pradesh','Tirap','Tissa','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,786630,'Arunachal Pradesh','Tirap','Tupi','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,786630,'Arunachal Pradesh','Tirap','Vally View','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,786631,'Arunachal Pradesh','Tirap','Wakka','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791111,'Arunachal Pradesh','Papum Pare','A P sectt.','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791112,'Arunachal Pradesh','Papum Pare','Arunachal University','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791123,'Arunachal Pradesh','Papum Pare','Balijan','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791123,'Arunachal Pradesh','Papum Pare','Banderdewa','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791112,'Arunachal Pradesh','Papum Pare','Doimukh','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791113,'Arunachal Pradesh','Papum Pare','Donyi Polo','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791121,'Arunachal Pradesh','Papum Pare','Hawa Camp','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791111,'Arunachal Pradesh','Papum Pare','Itanagar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791112,'Arunachal Pradesh','Papum Pare','Kheel','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791121,'Arunachal Pradesh','Papum Pare','Kimin','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791123,'Arunachal Pradesh','Papum Pare','Kokila','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791112,'Arunachal Pradesh','Papum Pare','Midpu','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791110,'Arunachal Pradesh','Papum Pare','Model Village','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791110,'Arunachal Pradesh','Papum Pare','Naharlagun','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791109,'Arunachal Pradesh','Papum Pare','Nirjuli','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791113,'Arunachal Pradesh','Papum Pare','Ram Krishna mission','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791112,'Arunachal Pradesh','Papum Pare','Saglee','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791123,'Arunachal Pradesh','Papum Pare','Sonajuli','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791113,'Arunachal Pradesh','Papum Pare','Vivek Vihar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791110,'Arunachal Pradesh','Papum Pare','Yupia','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791120,'Arunachal Pradesh','Lower Subansiri','Boasimla','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791113,'Arunachal Pradesh','Lower Subansiri','Chimpu','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791120,'Arunachal Pradesh','Lower Subansiri','Deed','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791120,'Arunachal Pradesh','Lower Subansiri','Godak','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791120,'Arunachal Pradesh','Lower Subansiri','Hija','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791120,'Arunachal Pradesh','Lower Subansiri','Joram','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791119,'Arunachal Pradesh','Lower Subansiri','Mengio','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791120,'Arunachal Pradesh','Lower Subansiri','Old Ziro','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791120,'Arunachal Pradesh','Lower Subansiri','Raga','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791119,'Arunachal Pradesh','Lower Subansiri','Ranga Nadi project','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791120,'Arunachal Pradesh','Lower Subansiri','Talo','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791120,'Arunachal Pradesh','Lower Subansiri','Yachuli','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791119,'Arunachal Pradesh','Lower Subansiri','Yazali','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791120,'Arunachal Pradesh','Lower Subansiri','Ziro','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792101,'Arunachal Pradesh','Dibang Valley','Alinye','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792101,'Arunachal Pradesh','Dibang Valley','Anelih','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792101,'Arunachal Pradesh','Dibang Valley','Anini','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791002,'Arunachal Pradesh','Upper Siang','Geku','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792061,'Arunachal Pradesh','Upper Siang','Gelling','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791002,'Arunachal Pradesh','Upper Siang','Karko','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791002,'Arunachal Pradesh','Upper Siang','Mariyang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792061,'Arunachal Pradesh','Upper Siang','Migging','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791002,'Arunachal Pradesh','Upper Siang','Shimong','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792061,'Arunachal Pradesh','Upper Siang','Singa','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792061,'Arunachal Pradesh','Upper Siang','Tuting','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791002,'Arunachal Pradesh','Upper Siang','Yingkiong','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791102,'Arunachal Pradesh','East Siang','Adipasi','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791104,'Arunachal Pradesh','East Siang','Ayeng','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791102,'Arunachal Pradesh','East Siang','Balek','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791102,'Arunachal Pradesh','East Siang','Bilat','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791102,'Arunachal Pradesh','East Siang','Boleng','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791104,'Arunachal Pradesh','East Siang','Borguli','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791102,'Arunachal Pradesh','East Siang','Dalbing','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791102,'Arunachal Pradesh','East Siang','Damro','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791102,'Arunachal Pradesh','East Siang','Debing','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791102,'Arunachal Pradesh','East Siang','Gtc','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791103,'Arunachal Pradesh','East Siang','Hill Top','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791102,'Arunachal Pradesh','East Siang','Kebang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791102,'Arunachal Pradesh','East Siang','Korang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791102,'Arunachal Pradesh','East Siang','Koyu','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791102,'Arunachal Pradesh','East Siang','Ledum','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791104,'Arunachal Pradesh','East Siang','Mebo','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791104,'Arunachal Pradesh','East Siang','Namsing','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791102,'Arunachal Pradesh','East Siang','Nari','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791104,'Arunachal Pradesh','East Siang','Ngopok','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791102,'Arunachal Pradesh','East Siang','Oyan','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791102,'Arunachal Pradesh','East Siang','Pangin','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791102,'Arunachal Pradesh','East Siang','Pasighat','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791102,'Arunachal Pradesh','East Siang','Rani','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791102,'Arunachal Pradesh','East Siang','Renging','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791102,'Arunachal Pradesh','East Siang','Riga','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791102,'Arunachal Pradesh','East Siang','Ruksin','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791102,'Arunachal Pradesh','East Siang','Sille','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791104,'Arunachal Pradesh','East Siang','Silluk','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791104,'Arunachal Pradesh','East Siang','Sirem','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791102,'Arunachal Pradesh','East Siang','Yagrung','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792110,'Arunachal Pradesh','Lower Dibang valley','Abango','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792110,'Arunachal Pradesh','Lower Dibang valley','Anupam','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792110,'Arunachal Pradesh','Lower Dibang valley','Bijari','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792110,'Arunachal Pradesh','Lower Dibang valley','Bolung','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792110,'Arunachal Pradesh','Lower Dibang valley','Bomjir','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792110,'Arunachal Pradesh','Lower Dibang valley','Dambuk','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792110,'Arunachal Pradesh','Lower Dibang valley','Desali','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792110,'Arunachal Pradesh','Lower Dibang valley','Elopa','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792110,'Arunachal Pradesh','Lower Dibang valley','Etalin','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792110,'Arunachal Pradesh','Lower Dibang valley','Hunli','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792110,'Arunachal Pradesh','Lower Dibang valley','Iduli','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792110,'Arunachal Pradesh','Lower Dibang valley','Jia','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792110,'Arunachal Pradesh','Lower Dibang valley','Koranu','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792110,'Arunachal Pradesh','Lower Dibang valley','Kronli','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792110,'Arunachal Pradesh','Lower Dibang valley','Meka','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792110,'Arunachal Pradesh','Lower Dibang valley','Paglam','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792110,'Arunachal Pradesh','Lower Dibang valley','Parbuk','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792110,'Arunachal Pradesh','Lower Dibang valley','Roing','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792110,'Arunachal Pradesh','Lower Dibang valley','Santipur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,790104,'Arunachal Pradesh','Tawang','B.Supply','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,790106,'Arunachal Pradesh','Tawang','Gispu','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,790105,'Arunachal Pradesh','Tawang','Jang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,790104,'Arunachal Pradesh','Tawang','Kitpi','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,790105,'Arunachal Pradesh','Tawang','Lhou','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,790104,'Arunachal Pradesh','Tawang','Lumberdung','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,790106,'Arunachal Pradesh','Tawang','Lumla','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,790105,'Arunachal Pradesh','Tawang','Mukto','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,790104,'Arunachal Pradesh','Tawang','Sakpret','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,790104,'Arunachal Pradesh','Tawang','Tawang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,790104,'Arunachal Pradesh','Tawang','Temple Gompa','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,790105,'Arunachal Pradesh','Tawang','Thingbu','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,790106,'Arunachal Pradesh','Tawang','Zimithang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791001,'Arunachal Pradesh','West Siang','Along','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791001,'Arunachal Pradesh','West Siang','Bagra','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791101,'Arunachal Pradesh','West Siang','Bame','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791101,'Arunachal Pradesh','West Siang','Basar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791001,'Arunachal Pradesh','West Siang','Bene','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791101,'Arunachal Pradesh','West Siang','Dali','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791001,'Arunachal Pradesh','West Siang','Darak','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791101,'Arunachal Pradesh','West Siang','Daring','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791001,'Arunachal Pradesh','West Siang','Darka','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791125,'Arunachal Pradesh','West Siang','Garu','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791125,'Arunachal Pradesh','West Siang','Gensi','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791001,'Arunachal Pradesh','West Siang','Kambang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791001,'Arunachal Pradesh','West Siang','Kaying','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791001,'Arunachal Pradesh','West Siang','Kombo','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791125,'Arunachal Pradesh','West Siang','Likabali','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791101,'Arunachal Pradesh','West Siang','Liromoba','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791001,'Arunachal Pradesh','West Siang','Logum Jining','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792051,'Arunachal Pradesh','West Siang','Mechuka','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791001,'Arunachal Pradesh','West Siang','Monigong','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791001,'Arunachal Pradesh','West Siang','Nikte','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791001,'Arunachal Pradesh','West Siang','Payum','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791001,'Arunachal Pradesh','West Siang','Rumgong','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791001,'Arunachal Pradesh','West Siang','Tato','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791101,'Arunachal Pradesh','West Siang','Tirbin','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791001,'Arunachal Pradesh','West Siang','Vivek Nagar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791001,'Arunachal Pradesh','West Siang','Yoji Yora','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791001,'Arunachal Pradesh','West Siang','Yomcha','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792102,'Arunachal Pradesh','Lohit','Alubari','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792102,'Arunachal Pradesh','Lohit','Chakma','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792001,'Arunachal Pradesh','Lohit','Changliang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792102,'Arunachal Pradesh','Lohit','Chowkham','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792001,'Arunachal Pradesh','Lohit','Danglat','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792103,'Arunachal Pradesh','Lohit','Diyun','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792001,'Arunachal Pradesh','Lohit','Gohaingaon','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792103,'Arunachal Pradesh','Lohit','Innao','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792103,'Arunachal Pradesh','Lohit','Jaipur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792102,'Arunachal Pradesh','Lohit','Kamlang Nagar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792102,'Arunachal Pradesh','Lohit','Kherem','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792051,'Arunachal Pradesh','Lohit','Kumari Kachari','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792103,'Arunachal Pradesh','Lohit','Kumsai','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792103,'Arunachal Pradesh','Lohit','Lathao','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792001,'Arunachal Pradesh','Lohit','Lohitpur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792001,'Arunachal Pradesh','Lohit','Loiliang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792051,'Arunachal Pradesh','Lohit','Mahadevpur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792103,'Arunachal Pradesh','Lohit','Manmao','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792102,'Arunachal Pradesh','Lohit','Medo','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792102,'Arunachal Pradesh','Lohit','Momong','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792103,'Arunachal Pradesh','Lohit','Nampong','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792103,'Arunachal Pradesh','Lohit','Namsai','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792103,'Arunachal Pradesh','Lohit','Nanam','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792103,'Arunachal Pradesh','Lohit','Peyong','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792051,'Arunachal Pradesh','Lohit','Podumani','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792111,'Arunachal Pradesh','Lohit','Sunpura','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792001,'Arunachal Pradesh','Lohit','Tafragram','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792001,'Arunachal Pradesh','Lohit','Tezu','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792001,'Arunachal Pradesh','Lohit','Tezu Covt.college','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792001,'Arunachal Pradesh','Lohit','Tindolong','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792103,'Arunachal Pradesh','Lohit','Udaipur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792102,'Arunachal Pradesh','Lohit','Wakro','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792103,'Arunachal Pradesh','Lohit','Wingko','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,792111,'Arunachal Pradesh','Lohit','Yealing','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791122,'Arunachal Pradesh','Upper Subansiri','Daporijo','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791122,'Arunachal Pradesh','Upper Subansiri','Dumporijo','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791122,'Arunachal Pradesh','Upper Subansiri','Giba','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791122,'Arunachal Pradesh','Upper Subansiri','Lemiking','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791122,'Arunachal Pradesh','Upper Subansiri','Lepajaring','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791122,'Arunachal Pradesh','Upper Subansiri','Maro','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791122,'Arunachal Pradesh','Upper Subansiri','Muri','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791122,'Arunachal Pradesh','Upper Subansiri','Nacho','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791122,'Arunachal Pradesh','Upper Subansiri','Sippi','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791122,'Arunachal Pradesh','Upper Subansiri','Siyum','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791122,'Arunachal Pradesh','Upper Subansiri','Tabarijo','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791122,'Arunachal Pradesh','Upper Subansiri','Taksing','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,791122,'Arunachal Pradesh','Upper Subansiri','Taliha','cc_in');
