insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,140119,'Chandigarh','Chandigarh','Abiana','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,160003,'Chandigarh','Chandigarh','Aerodrome','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,160004,'Chandigarh','Chandigarh','Airforce Highground','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,140125,'Chandigarh','Chandigarh','Ajauli','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,160036,'Chandigarh','Chandigarh','Badheri','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,140301,'Chandigarh','Chandigarh','Balongi','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,160003,'Chandigarh','Chandigarh','Behlana','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,160014,'Chandigarh','Chandigarh','Behlolpur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,160017,'Chandigarh','Chandigarh','Bus Stand','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,160017,'Chandigarh','Chandigarh','Chandigarh.','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,160014,'Chandigarh','Chandigarh','Dadu Majra colony','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,160101,'Chandigarh','Chandigarh','Daria','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,160014,'Chandigarh','Chandigarh','Dhanas','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,160012,'Chandigarh','Chandigarh','Engg College','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,160018,'Chandigarh','Chandigarh','Govt Press chandigarh','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,160002,'Chandigarh','Chandigarh','Hallomajra','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,160001,'Chandigarh','Chandigarh','High Court','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,160002,'Chandigarh','Chandigarh','Ind Area chandigarh','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,140133,'Chandigarh','Chandigarh','Kalitran','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,160025,'Chandigarh','Chandigarh','Maloya Colony','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,160101,'Chandigarh','Chandigarh','Manimajra','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,160101,'Chandigarh','Chandigarh','Manimajra Mt','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,160102,'Chandigarh','Chandigarh','Mauli Jagran','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,160101,'Chandigarh','Chandigarh','Mhc Manimajra','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,160002,'Chandigarh','Chandigarh','New Ind area','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,160001,'Chandigarh','Chandigarh','New Sectt chandigarh','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,160102,'Chandigarh','Chandigarh','Raipur Kalan','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,160019,'Chandigarh','Chandigarh','Raj Bhawan','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,160002,'Chandigarh','Chandigarh','Ram Darbar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,160011,'Chandigarh','Chandigarh','Sector 10 (chandigarh)','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,160011,'Chandigarh','Chandigarh','Sector 11( chandigarh)','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,160012,'Chandigarh','Chandigarh','Sector 12 (chandigarh)','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,160014,'Chandigarh','Chandigarh','Sector 14 (chandigarh)','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,160015,'Chandigarh','Chandigarh','Sector 15 chandigarh','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,160015,'Chandigarh','Chandigarh','Sector 16 (chandigarh)','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,160018,'Chandigarh','Chandigarh','Sector 18 (chandigarh)','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,160019,'Chandigarh','Chandigarh','Sector 19 (chandigarh)','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,160020,'Chandigarh','Chandigarh','Sector 20 (chandigarh)','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,160022,'Chandigarh','Chandigarh','Sector 21 (chandigarh)','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,160022,'Chandigarh','Chandigarh','Sector 22 (chandigarh)','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,160023,'Chandigarh','Chandigarh','Sector 23 ( chandigarh)','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,160019,'Chandigarh','Chandigarh','Sector 26 (chandigarh)','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,160019,'Chandigarh','Chandigarh','Sector 27 (chandigarh)','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,160030,'Chandigarh','Chandigarh','Sector 29 (chandigarh)','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,160030,'Chandigarh','Chandigarh','Sector 30 (chandigarh)','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,160030,'Chandigarh','Chandigarh','Sector 31 (chandigarh','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,160022,'Chandigarh','Chandigarh','Sector 34 (chandigarh)','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,160035,'Chandigarh','Chandigarh','Sector 35 (chandigarh)','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,160036,'Chandigarh','Chandigarh','Sector 36 (chandigarh)','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,160036,'Chandigarh','Chandigarh','Sector 40 (chandigarh)','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,160047,'Chandigarh','Chandigarh','Sector 44 (chandigarh)','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,160047,'Chandigarh','Chandigarh','Sector 46 (chandigarh)','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,160047,'Chandigarh','Chandigarh','Sector 47 chandigarh','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,160009,'Chandigarh','Chandigarh','Sector 8 (chandgarh)','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,160009,'Chandigarh','Chandigarh','Sector 9 (chandigarh)','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,160014,'Chandigarh','Chandigarh','Tira','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,160001,'Chandigarh','Chandigarh','Vidhansadan','cc_in');
