insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,362570,'Daman And diu','Diu','Bucharvada','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,362520,'Daman And diu','Diu','Diu','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,362520,'Daman And diu','Diu','Diu Zampa','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,362520,'Daman And diu','Diu','Fudam','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,362540,'Daman And diu','Diu','Ghoghla','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,362570,'Daman And diu','Diu','Wanakbara','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,396210,'Daman And diu','Daman','Bhimpore','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,396215,'Daman And diu','Daman','Dabhel','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,396210,'Daman And diu','Daman','Daman','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,396215,'Daman And diu','Daman','Daman I.e.','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,396220,'Daman And diu','Daman','Dholar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,396210,'Daman And diu','Daman','Dunetha','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,396215,'Daman And diu','Daman','Kachigam','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,396210,'Daman And diu','Daman','Kadaiya','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,396215,'Daman And diu','Daman','Kunta','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,396220,'Daman And diu','Daman','Magarwada','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,396210,'Daman And diu','Daman','Marvad','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,396220,'Daman And diu','Daman','Moti Daman','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,396210,'Daman And diu','Daman','Nani Vankad','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,396210,'Daman And diu','Daman','Varkund','cc_in');
