insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110025,'Delhi','South Delhi','Abul Fazal enclave-i','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110062,'Delhi','South Delhi','Air Force station tugalkabad','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110019,'Delhi','South Delhi','Alaknanda','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110019,'Delhi','South Delhi','Ali','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110003,'Delhi','South Delhi','Aliganj','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110024,'Delhi','South Delhi','Amar Colony','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110049,'Delhi','South Delhi','Andrewsganj','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110044,'Delhi','South Delhi','Btps','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110044,'Delhi','South Delhi','Badarpur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110062,'Delhi','South Delhi','Bsf Camp tigri','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110003,'Delhi','South Delhi','C G o complex','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110020,'Delhi','South Delhi','C R r i','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110017,'Delhi','South Delhi','Chirag Delhi','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110019,'Delhi','South Delhi','Chittranjan Park','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110062,'Delhi','South Delhi','Dakshinpuri Phase-i','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110062,'Delhi','South Delhi','Dakshinpuri Phase-ii','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110062,'Delhi','South Delhi','Dakshinpuri Phase-iii','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110013,'Delhi','South Delhi','Dargah Sharif','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110024,'Delhi','South Delhi','Defence Colony','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110062,'Delhi','South Delhi','Deoli','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110062,'Delhi','South Delhi','Dr. ambedkar nagar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110065,'Delhi','South Delhi','East Of kailash','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110065,'Delhi','South Delhi','East Of kailash phase-i','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110049,'Delhi','South Delhi','Gautam Nagar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110003,'Delhi','South Delhi','Golf Links','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110019,'Delhi','South Delhi','Govindpuri','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110048,'Delhi','South Delhi','Greater Kailash','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110048,'Delhi','South Delhi','Greater Kailash part ii','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110049,'Delhi','South Delhi','Gulmohar Park','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110062,'Delhi','South Delhi','Hamdard Nagar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110014,'Delhi','South Delhi','Hari Nagar ashram','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110013,'Delhi','South Delhi','Hazrat Nizamuddin','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110044,'Delhi','South Delhi','Jaitpur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110025,'Delhi','South Delhi','Jamia Nagar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110014,'Delhi','South Delhi','Jeevan Nagar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110014,'Delhi','South Delhi','Jungpura','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110048,'Delhi','South Delhi','Kailash Colony','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110019,'Delhi','South Delhi','Kalkaji','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110003,'Delhi','South Delhi','Kasturba Nagar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110062,'Delhi','South Delhi','Khanpur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110024,'Delhi','South Delhi','Krishna Market','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110024,'Delhi','South Delhi','Lajpat Nagar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110019,'Delhi','South Delhi','Lal Kuan','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110003,'Delhi','South Delhi','Lodi Colony market','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110003,'Delhi','South Delhi','Lodi Road','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110017,'Delhi','South Delhi','Mmtc/stc Colony','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110076,'Delhi','South Delhi','Madanpur Khadar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110017,'Delhi','South Delhi','Malviya Nagar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110048,'Delhi','South Delhi','Masjid Moth','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110044,'Delhi','South Delhi','Molarband','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110065,'Delhi','South Delhi','Nehru Nagar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110019,'Delhi','South Delhi','Nehru Place','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110049,'Delhi','South Delhi','New Delhi south ext-ii','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110025,'Delhi','South Delhi','New Friends colony','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110020,'Delhi','South Delhi','Okhla Industrial area phase-i','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110020,'Delhi','South Delhi','Okhla Industrial estate','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110017,'Delhi','South Delhi','Panchsheel Enclave','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110003,'Delhi','South Delhi','Pragati Vihar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110014,'Delhi','South Delhi','Pratap Market','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110044,'Delhi','South Delhi','Pul Pahladpur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110017,'Delhi','South Delhi','Pushp Vihar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110062,'Delhi','South Delhi','Pushpa Bhawan','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110049,'Delhi','South Delhi','Sadiq Nagar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110003,'Delhi','South Delhi','Safdarjung Air port','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110049,'Delhi','South Delhi','Sahpurjat','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110017,'Delhi','South Delhi','Saket','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110065,'Delhi','South Delhi','Sant Nagar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110076,'Delhi','South Delhi','Sarita Vihar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110017,'Delhi','South Delhi','Sarvodya Enclave','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110017,'Delhi','South Delhi','South Malviya nagar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110065,'Delhi','South Delhi','Sriniwaspuri','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110025,'Delhi','South Delhi','Sukhdev Vihar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110062,'Delhi','South Delhi','Talimabad','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110019,'Delhi','South Delhi','Tehkhand','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110019,'Delhi','South Delhi','Tugalkabad','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110044,'Delhi','South Delhi','Tugalkabad Railway colony','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110025,'Delhi','South Delhi','Zakir Nagar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110033,'Delhi','North West delhi','Adrash Nagar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110036,'Delhi','North West delhi','Alipur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110034,'Delhi','North West delhi','Anandvas Shakurpur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110052,'Delhi','North West delhi','Ashok Vihar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110039,'Delhi','North West delhi','Auchandi','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110042,'Delhi','North West delhi','Badli','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110036,'Delhi','North West delhi','Bakhtawar Pur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110036,'Delhi','North West delhi','Bakoli','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110040,'Delhi','North West delhi','Bankner','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110039,'Delhi','North West delhi','Barwala','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110039,'Delhi','North West delhi','Bawana','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110086,'Delhi','North West delhi','Begumpur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110033,'Delhi','North West delhi','Bhalaswa','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110040,'Delhi','North West delhi','Bhorgarh','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110086,'Delhi','North West delhi','Budh Vihar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110081,'Delhi','North West delhi','Chand Pur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110042,'Delhi','North West delhi','Delhi Engg. college','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110009,'Delhi','North West delhi','Dr.Mukerjee nagar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110009,'Delhi','North West delhi','G.T.b.nagar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110035,'Delhi','North West delhi','Ganeshpura','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110081,'Delhi','North West delhi','Gheora','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110039,'Delhi','North West delhi','Ghoga','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110009,'Delhi','North West delhi','Gujranwala Colony','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110009,'Delhi','North West delhi','H.S.sangh','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110088,'Delhi','North West delhi','Haiderpur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110039,'Delhi','North West delhi','Hareveli','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110036,'Delhi','North West delhi','Hiranki','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110082,'Delhi','North West delhi','Holambi Kalan','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110035,'Delhi','North West delhi','Inderlok','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110033,'Delhi','North West delhi','Jahangir Puri a block','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110033,'Delhi','North West delhi','Jahangir Puri d block','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110033,'Delhi','North West delhi','Jahangir Puri h block','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110039,'Delhi','North West delhi','Jat Khore','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110081,'Delhi','North West delhi','Jaunti','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110036,'Delhi','North West delhi','Kadipur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110081,'Delhi','North West delhi','Kanjhawla','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110040,'Delhi','North West delhi','Kanya Gurukul','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110081,'Delhi','North West delhi','Karala','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110039,'Delhi','North West delhi','Katewara','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110035,'Delhi','North West delhi','Keshav Puram','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110036,'Delhi','North West delhi','Khampur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110082,'Delhi','North West delhi','Khera Kalan','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110082,'Delhi','North West delhi','Khera Khurd','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110081,'Delhi','North West delhi','Lad Pur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110040,'Delhi','North West delhi','Lampur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110081,'Delhi','North West delhi','Majra Dabas','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110083,'Delhi','North West delhi','Mangolpuri A block','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110083,'Delhi','North West delhi','Mangolpuri I block','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110083,'Delhi','North West delhi','Mangolpuri N block','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110083,'Delhi','North West delhi','Mangolpuri S block','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110034,'Delhi','North West delhi','Maurya Enclave','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110009,'Delhi','North West delhi','Model Town ii','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110009,'Delhi','North West delhi','Model Town iii','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110081,'Delhi','North West delhi','Mubarak Pur dabas','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110036,'Delhi','North West delhi','Mukhmelpur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110033,'Delhi','North West delhi','N.S.mandi','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110006,'Delhi','North West delhi','Nangal Poona','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110039,'Delhi','North West delhi','Nangal Thakran','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110040,'Delhi','North West delhi','Narela','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110040,'Delhi','North West delhi','Narela Town','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110082,'Delhi','North West delhi','Naya Bans','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110052,'Delhi','North West delhi','Nimri','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110009,'Delhi','North West delhi','Nirankari Colony','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110081,'Delhi','North West delhi','Nizampur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110035,'Delhi','North West delhi','Onkar Nagar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110036,'Delhi','North West delhi','Palla','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110042,'Delhi','North West delhi','Pehlad Pur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110086,'Delhi','North West delhi','Pooth Kalan','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110086,'Delhi','North West delhi','Pooth Kalan resettlement','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110039,'Delhi','North West delhi','Pooth Khurd','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110035,'Delhi','North West delhi','Power House','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110085,'Delhi','North West delhi','Prashant Vihar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110081,'Delhi','North West delhi','Punjab Khor','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110039,'Delhi','North West delhi','Qutabagarh','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110035,'Delhi','North West delhi','Rampura','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110034,'Delhi','North West delhi','Rani Bagh','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110081,'Delhi','North West delhi','Rani Khera','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110085,'Delhi','North West delhi','Rithala','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110085,'Delhi','North West delhi','Rohini Courts','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110089,'Delhi','North West delhi','Rohini Sector 15','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110085,'Delhi','North West delhi','Rohini Sector 5','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110085,'Delhi','North West delhi','Rohini Sector-7','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110042,'Delhi','North West delhi','Samai Pur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110035,'Delhi','North West delhi','Sarai Rohilla','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110034,'Delhi','North West delhi','Saraswati Vihar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110052,'Delhi','North West delhi','Satyawati Nagar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110056,'Delhi','North West delhi','Shakur Basti depot','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110034,'Delhi','North West delhi','Shakur Pur i block','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110034,'Delhi','North West delhi','Shakurbasti Rs','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110088,'Delhi','North West delhi','Shalamar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110088,'Delhi','North West delhi','Shalimar Bagh','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110052,'Delhi','North West delhi','Shastri Nagar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110040,'Delhi','North West delhi','Singhu','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110042,'Delhi','North West delhi','Siraspur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110034,'Delhi','North West delhi','Sri Nagar colony','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110086,'Delhi','North West delhi','Sultanpuri B block','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110086,'Delhi','North West delhi','Sultanpuri C block','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110086,'Delhi','North West delhi','Sultanpuri F block','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110036,'Delhi','North West delhi','Tajpur Kalan','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110052,'Delhi','North West delhi','Wazir Pur iii','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110002,'Delhi','Central Delhi','A.G.c.r.','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110055,'Delhi','Central Delhi','A.K.market','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110002,'Delhi','Central Delhi','Ajmeri Gate extn.','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110005,'Delhi','Central Delhi','Anand Parbat','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110005,'Delhi','Central Delhi','Anand Parbat indl. area','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110005,'Delhi','Central Delhi','Bank Street','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110001,'Delhi','Central Delhi','Baroda House','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110001,'Delhi','Central Delhi','Bengali Market','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110001,'Delhi','Central Delhi','Bhagat Singh market','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110001,'Delhi','Central Delhi','Connaught Place','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110001,'Delhi','Central Delhi','Constitution House','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110008,'Delhi','Central Delhi','Dada Ghosh bhawan','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110002,'Delhi','Central Delhi','Darya Ganj','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110003,'Delhi','Central Delhi','Delhi High court','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110005,'Delhi','Central Delhi','Desh Bandhu gupta road','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110001,'Delhi','Central Delhi','Election Commission','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110002,'Delhi','Central Delhi','Gandhi Smarak nidhi','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110005,'Delhi','Central Delhi','Guru Gobind singh marg','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110011,'Delhi','Central Delhi','Gym Khana club','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110006,'Delhi','Central Delhi','Hauz Qazi','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110012,'Delhi','Central Delhi','I.A.r.i.','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110002,'Delhi','Central Delhi','I.P.estate','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110012,'Delhi','Central Delhi','Inderpuri','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110002,'Delhi','Central Delhi','Indraprastha','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110006,'Delhi','Central Delhi','Jama Masjid','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110001,'Delhi','Central Delhi','Janpath','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110005,'Delhi','Central Delhi','Karol Bagh','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110001,'Delhi','Central Delhi','Krishi Bhawan','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110001,'Delhi','Central Delhi','Lady Harding medical college','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110005,'Delhi','Central Delhi','Master Prithvi nath marg','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110002,'Delhi','Central Delhi','Minto Road','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110055,'Delhi','Central Delhi','Multani Dhanda','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110012,'Delhi','Central Delhi','National Physical laboratory','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110011,'Delhi','Central Delhi','Nirman Bhawan','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110001,'Delhi','Central Delhi','North Avenue','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110055,'Delhi','Central Delhi','Pahar Ganj','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110003,'Delhi','Central Delhi','Pandara Road','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110001,'Delhi','Central Delhi','Parliament House','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110008,'Delhi','Central Delhi','Patel Nagar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110008,'Delhi','Central Delhi','Patel Nagar east','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110008,'Delhi','Central Delhi','Patel Nagar south','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110008,'Delhi','Central Delhi','Patel Nagar west','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110001,'Delhi','Central Delhi','Patiala House','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110001,'Delhi','Central Delhi','Pragati Maidan','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110001,'Delhi','Central Delhi','Rail Bhawan','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110060,'Delhi','Central Delhi','Rajender Nagar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110002,'Delhi','Central Delhi','Rajghat Power house','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110004,'Delhi','Central Delhi','Rashtrapati Bhawan','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110001,'Delhi','Central Delhi','Sansad Marg','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110001,'Delhi','Central Delhi','Sansadiya Soudh','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110005,'Delhi','Central Delhi','Sat Nagar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110001,'Delhi','Central Delhi','Secretariat North','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110001,'Delhi','Central Delhi','Shastri Bhawan','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110011,'Delhi','Central Delhi','South Avenue','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110001,'Delhi','Central Delhi','Supreme Court','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110055,'Delhi','Central Delhi','Swami Ram tirth nagar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110011,'Delhi','Central Delhi','Udyog Bhawan','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110069,'Delhi','Central Delhi','Union Public service commissio','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110092,'Delhi','East Delhi','Anand Vihar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110051,'Delhi','East Delhi','Azad Nagar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110032,'Delhi','East Delhi','Babarpur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110032,'Delhi','East Delhi','Balbir Nagar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110053,'Delhi','East Delhi','Bhajan Pura','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110032,'Delhi','East Delhi','Bhola Nath nagar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110053,'Delhi','East Delhi','Brahampuri','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110091,'Delhi','East Delhi','Chilla','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110094,'Delhi','East Delhi','Dayalpur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110095,'Delhi','East Delhi','Dilshad Garden','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110032,'Delhi','East Delhi','Distt. court (kkd)','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110095,'Delhi','East Delhi','G.T.b. hospital','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110031,'Delhi','East Delhi','Gandhi Nagar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110031,'Delhi','East Delhi','Gandhi Nagar bazar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110031,'Delhi','East Delhi','Geeta Colony','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110096,'Delhi','East Delhi','Ghazipur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110053,'Delhi','East Delhi','Ghonda','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110094,'Delhi','East Delhi','Gokal Puri','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110032,'Delhi','East Delhi','Goverdhan Bihari colony','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110051,'Delhi','East Delhi','Govind Pura','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110091,'Delhi','East Delhi','Himmatpuri','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110053,'Delhi','East Delhi','Jafrabad','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110053,'Delhi','East Delhi','Jagjit Nagar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110095,'Delhi','East Delhi','Jhilmil','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110095,'Delhi','East Delhi','Jhilmil Tahirpur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110094,'Delhi','East Delhi','Johripur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110031,'Delhi','East Delhi','Kailash Nagar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110091,'Delhi','East Delhi','Kalyanpuri','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110091,'Delhi','East Delhi','Kalyanvas','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110094,'Delhi','East Delhi','Karawal Nagar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110094,'Delhi','East Delhi','Khazuri Khas','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110051,'Delhi','East Delhi','Krishna Nagar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110092,'Delhi','East Delhi','Laxmi Nagar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110032,'Delhi','East Delhi','Loni Road','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110093,'Delhi','East Delhi','Loni Road housing complex','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110032,'Delhi','East Delhi','Man Sarovar park','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110092,'Delhi','East Delhi','Mandawali Fazalpur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110093,'Delhi','East Delhi','Mandoli Saboli','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110053,'Delhi','East Delhi','Maujpur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110091,'Delhi','East Delhi','Mayur Vihar ph-i','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110096,'Delhi','East Delhi','Mayur Vihar ph-iii','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110093,'Delhi','East Delhi','Nand Nagri "a"','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110093,'Delhi','East Delhi','Nand Nagri "c"','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110095,'Delhi','East Delhi','New Seemapuri','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110053,'Delhi','East Delhi','New Usmanpur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110092,'Delhi','East Delhi','Nirman Vihar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110095,'Delhi','East Delhi','Old Seemapuri','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110091,'Delhi','East Delhi','Patparganj','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110031,'Delhi','East Delhi','Raghubar Pura','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110031,'Delhi','East Delhi','Rajgarh Colony','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110051,'Delhi','East Delhi','Ram Nagar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110032,'Delhi','East Delhi','Rohtash Nagar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110094,'Delhi','East Delhi','Sabhapur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110053,'Delhi','East Delhi','Seelampur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110032,'Delhi','East Delhi','Shahdara','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110032,'Delhi','East Delhi','Shahdara Mandi','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110092,'Delhi','East Delhi','Shakarpur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110031,'Delhi','East Delhi','Shastri Nagar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110032,'Delhi','East Delhi','Shivaji Park','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110094,'Delhi','East Delhi','Sonia Vihar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110092,'Delhi','East Delhi','Surajmal Vihar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110032,'Delhi','East Delhi','Telewara','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110091,'Delhi','East Delhi','Trilok Puri','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110095,'Delhi','East Delhi','V.K. nagar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110096,'Delhi','East Delhi','Vasundhra Enclave','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110032,'Delhi','East Delhi','Vishwas Nagar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110095,'Delhi','East Delhi','Vivek Vihar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110053,'Delhi','East Delhi','Yamuna Vihar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110092,'Delhi','East Delhi','Yozna Vihar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110006,'Delhi','North Delhi','Baratooti','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110007,'Delhi','North Delhi','Birla Lines','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110084,'Delhi','North Delhi','Burari','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110007,'Delhi','North Delhi','C.C.i.','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110006,'Delhi','North Delhi','Chandni Chowk','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110006,'Delhi','North Delhi','Chawri Bazar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110054,'Delhi','North Delhi','Civil Lines','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110006,'Delhi','North Delhi','Dareeba','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110006,'Delhi','North Delhi','Delhi Sadar bazar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110007,'Delhi','North Delhi','Delhi University','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110054,'Delhi','North Delhi','Distt Courts','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110007,'Delhi','North Delhi','Gulabi Bagh','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110084,'Delhi','North Delhi','Jagatpur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110007,'Delhi','North Delhi','Jawahar Nagar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110084,'Delhi','North Delhi','Jharoda Majraa','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110007,'Delhi','North Delhi','Kamla Nagar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110007,'Delhi','North Delhi','Malka Ganj','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110007,'Delhi','North Delhi','Padam Nagar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110054,'Delhi','North Delhi','Patrachar Vidyalay','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110007,'Delhi','North Delhi','R.C.a.o.','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110007,'Delhi','North Delhi','Rana Pratap bagh','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110007,'Delhi','North Delhi','Roop Nagar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110007,'Delhi','North Delhi','Roshan Ara road','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110006,'Delhi','North Delhi','S.T. road','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110007,'Delhi','North Delhi','Shakti Nagar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110054,'Delhi','North Delhi','Timarpur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110020,'Delhi','New Delhi','F F c okhla','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110001,'Delhi','New Delhi','New Delhi','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110001,'Delhi','New Delhi','New Delhi.','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110058,'Delhi','West Delhi','A-3 Janak puri','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110018,'Delhi','West Delhi','Ashok Nagar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110026,'Delhi','West Delhi','Ashoka Park extn.','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110058,'Delhi','West Delhi','B-1 Janak puri','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110015,'Delhi','West Delhi','Bakkarwala','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110058,'Delhi','West Delhi','C-4 Janak puri','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110018,'Delhi','West Delhi','Chand Nagar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110015,'Delhi','West Delhi','Chaukhandi','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110059,'Delhi','West Delhi','D. k. mohan garden','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110058,'Delhi','West Delhi','D.E.s.u. colony','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110015,'Delhi','West Delhi','Delhi Industrial area','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110015,'Delhi','West Delhi','Esi','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110018,'Delhi','West Delhi','Fateh Nagar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110064,'Delhi','West Delhi','Hari Nagar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110064,'Delhi','West Delhi','Hari Nagar be block','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110064,'Delhi','West Delhi','Hari Nagar dadb block','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110015,'Delhi','West Delhi','Hastal Village','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110015,'Delhi','West Delhi','Hirankudna','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110027,'Delhi','West Delhi','J-6 Rajouri garden','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110058,'Delhi','West Delhi','Jail Road','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110027,'Delhi','West Delhi','Janta Market','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110063,'Delhi','West Delhi','Jawala Heri','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110059,'Delhi','West Delhi','Jeevan Park','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110087,'Delhi','West Delhi','Jwala Puri','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110015,'Delhi','West Delhi','Jwalaheri','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110015,'Delhi','West Delhi','Karam Pura','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110018,'Delhi','West Delhi','Khyala Phase - i','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110018,'Delhi','West Delhi','Khyala Phase - ii','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110015,'Delhi','West Delhi','L. m. nagar indl. area','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110018,'Delhi','West Delhi','M.B.s. nagar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110063,'Delhi','West Delhi','Madipur Slum quarter','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110063,'Delhi','West Delhi','Madipur Village','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110018,'Delhi','West Delhi','Mahabir Nagar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110015,'Delhi','West Delhi','Mansarover Garden','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110059,'Delhi','West Delhi','Matiala','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110041,'Delhi','West Delhi','Mundka','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110015,'Delhi','West Delhi','N.I.area','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110041,'Delhi','West Delhi','Nangloi','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110015,'Delhi','West Delhi','Nangloi - ii','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110041,'Delhi','West Delhi','Nangloi - iii','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110015,'Delhi','West Delhi','Nilothi','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110063,'Delhi','West Delhi','Paschim Vihar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110063,'Delhi','West Delhi','Paschim Vihar b block','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110015,'Delhi','West Delhi','Peeragarhi','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110026,'Delhi','West Delhi','Punjabi Bagh','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110026,'Delhi','West Delhi','Punjabi Bagh sec - iii','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110027,'Delhi','West Delhi','Rajouri Garden','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110027,'Delhi','West Delhi','Rajouri Market','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110015,'Delhi','West Delhi','Ramesh Nagar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110015,'Delhi','West Delhi','Ranhola','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110026,'Delhi','West Delhi','Shivaji Park','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110027,'Delhi','West Delhi','Subhash Nagar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110027,'Delhi','West Delhi','Subhash Nagar west','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110087,'Delhi','West Delhi','Sunder Vihar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110015,'Delhi','West Delhi','Tikri Kalan','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110018,'Delhi','West Delhi','Tilak Nagar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110018,'Delhi','West Delhi','Tilak Nagar east','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110059,'Delhi','West Delhi','Uttam Nagar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110018,'Delhi','West Delhi','Vikas Puri','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110018,'Delhi','West Delhi','Vishnu Garden','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110015,'Delhi','West Delhi','Zakhira','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110010,'Delhi','South West delhi','505 A b workshop','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110010,'Delhi','South West delhi','A F palam','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110038,'Delhi','South West delhi','A F rajokari','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110075,'Delhi','South West delhi','Amberhai','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110021,'Delhi','South West delhi','Anand Niketan','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110029,'Delhi','South West delhi','Ansari Nagar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110010,'Delhi','South West delhi','Aps Colony','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110047,'Delhi','South West delhi','Arjungarh','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110047,'Delhi','South West delhi','Aya Nagar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110028,'Delhi','South West delhi','Badhosarai','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110071,'Delhi','South West delhi','Badusarai','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110077,'Delhi','South West delhi','Bagrola','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110028,'Delhi','South West delhi','Baprola','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110077,'Delhi','South West delhi','Barthal','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110010,'Delhi','South West delhi','Bazar Road','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110061,'Delhi','South West delhi','Bijwasan','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110074,'Delhi','South West delhi','C.S.k.m. school','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110010,'Delhi','South West delhi','C.V.d.','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110010,'Delhi','South West delhi','Cod','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110072,'Delhi','South West delhi','Crpf Jharoda kalan','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110021,'Delhi','South West delhi','Chanakya Puri','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110074,'Delhi','South West delhi','Chandanhoola','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110074,'Delhi','South West delhi','Chattarpur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110071,'Delhi','South West delhi','Chhawla','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110028,'Delhi','South West delhi','D C goyla','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110028,'Delhi','South West delhi','D C nangli sakravati','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110028,'Delhi','South West delhi','Dabri','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110028,'Delhi','South West delhi','Daulatpur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110010,'Delhi','South West delhi','Delhi Cantt','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110074,'Delhi','South West delhi','Dera','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110073,'Delhi','South West delhi','Dhansa','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110010,'Delhi','South West delhi','Dhaula Kuan','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110077,'Delhi','South West delhi','Dhulsiras','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110028,'Delhi','South West delhi','Dichaoal Kalan','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110028,'Delhi','South West delhi','Dindarpur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110028,'Delhi','South West delhi','Dulsiras','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110075,'Delhi','South West delhi','Dwarka Sec-6','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110074,'Delhi','South West delhi','Fatehpur Beri','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110030,'Delhi','South West delhi','Gadaipur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110028,'Delhi','South West delhi','Galib Pur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110030,'Delhi','South West delhi','Ghitorni','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110028,'Delhi','South West delhi','Ghuman Hera','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110016,'Delhi','South West delhi','Green Park market','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110037,'Delhi','South West delhi','Gurgaon Road','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110016,'Delhi','South West delhi','Hauz Khas','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110016,'Delhi','South West delhi','Hauz Khas market','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110037,'Delhi','South West delhi','Igi Airport','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110016,'Delhi','South West delhi','It Hauz khas','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110068,'Delhi','South West delhi','Ignou','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110045,'Delhi','South West delhi','Indira Park','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110073,'Delhi','South West delhi','Issapur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110067,'Delhi','South West delhi','J.N.u.','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110067,'Delhi','South West delhi','Jnu New campus','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110028,'Delhi','South West delhi','Jafarpur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110047,'Delhi','South West delhi','Jaunapur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110028,'Delhi','South West delhi','Jharoda Kalan','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110028,'Delhi','South West delhi','Jhatikara','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110043,'Delhi','South West delhi','Kair','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110078,'Delhi','South West delhi','Kakrola','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110028,'Delhi','South West delhi','Kangan Heri','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110037,'Delhi','South West delhi','Kapashera','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110043,'Delhi','South West delhi','Khaira','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110028,'Delhi','South West delhi','Khera Dabur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110023,'Delhi','South West delhi','Kidwai Nagar east','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110023,'Delhi','South West delhi','Kidwai Nagar west','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110010,'Delhi','South West delhi','Kirby Place','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110030,'Delhi','South West delhi','Lado Sarai','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110023,'Delhi','South West delhi','Laxmi Bai nagar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110037,'Delhi','South West delhi','Mahipalpur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110068,'Delhi','South West delhi','Maidan Garhi','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110021,'Delhi','South West delhi','Malcha Marg','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110073,'Delhi','South West delhi','Malik Pur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110047,'Delhi','South West delhi','Mandi','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110070,'Delhi','South West delhi','Masood Pur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110064,'Delhi','South West delhi','Maya Puri','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110030,'Delhi','South West delhi','Mehrauli','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110028,'Delhi','South West delhi','Mitraon','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110021,'Delhi','South West delhi','Moti Bagh','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110028,'Delhi','South West delhi','Mundela Kalan','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110067,'Delhi','South West delhi','Munirka','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110078,'Delhi','South West delhi','N.S.i.t. dwarka','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110016,'Delhi','South West delhi','Nie Campus','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110043,'Delhi','South West delhi','Najafgarh','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110021,'Delhi','South West delhi','Nanak Pura','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110037,'Delhi','South West delhi','Nangal Dewat','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110046,'Delhi','South West delhi','Nangal Raya','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110028,'Delhi','South West delhi','Naraina Industrial estate','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110028,'Delhi','South West delhi','Naraina Village','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110028,'Delhi','South West delhi','Nasirpur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110029,'Delhi','South West delhi','Nauroji Nagar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110068,'Delhi','South West delhi','Neb Sarai','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110023,'Delhi','South West delhi','Netaji Nagar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110037,'Delhi','South West delhi','Palam Airport','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110045,'Delhi','South West delhi','Palam Village','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110028,'Delhi','South West delhi','Pandwala Kalan','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110028,'Delhi','South West delhi','Papravat','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110030,'Delhi','South West delhi','Paryavaran Complex','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110010,'Delhi','South West delhi','Pinto Park','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110022,'Delhi','South West delhi','Postal Sb r.k.puram sector-6','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110028,'Delhi','South West delhi','Quazipur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110066,'Delhi','South West delhi','R K puram (main)','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110022,'Delhi','South West delhi','R K puram sect-1','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110022,'Delhi','South West delhi','R K puram sect-12','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110022,'Delhi','South West delhi','R K puram sect-3','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110022,'Delhi','South West delhi','R K puram sect-4','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110022,'Delhi','South West delhi','R K puram sect-5','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110022,'Delhi','South West delhi','R K puram sect-8','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110022,'Delhi','South West delhi','R K puram sect7','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110066,'Delhi','South West delhi','R K puram west','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110010,'Delhi','South West delhi','R R hospital','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110077,'Delhi','South West delhi','Raj Nagar - ii','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110038,'Delhi','South West delhi','Rajokari','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110073,'Delhi','South West delhi','Raota','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110028,'Delhi','South West delhi','Rewla Khanpur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110029,'Delhi','South West delhi','S J enclave','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110074,'Delhi','South West delhi','S P school','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110046,'Delhi','South West delhi','Sagarpur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110037,'Delhi','South West delhi','Samalkha','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110023,'Delhi','South West delhi','Sarojini Nagar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110074,'Delhi','South West delhi','Satbari','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110061,'Delhi','South West delhi','Shahbad Mohammadpur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110064,'Delhi','South West delhi','Shopping Centre mayapuri','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110010,'Delhi','South West delhi','Signal Enclave','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110021,'Delhi','South West delhi','South Delhi campus','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110010,'Delhi','South West delhi','Station Road','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110010,'Delhi','South West delhi','Subroto Park','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110030,'Delhi','South West delhi','Sultanpur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110028,'Delhi','South West delhi','Surehra','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110030,'Delhi','South West delhi','T B hospital','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110016,'Delhi','South West delhi','Technology Bhawan','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110028,'Delhi','South West delhi','Tilangpur Kotla','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110073,'Delhi','South West delhi','Ujwa','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110070,'Delhi','South West delhi','Vasant Kunj','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110070,'Delhi','South West delhi','Vasant Kunj pkt-a','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110057,'Delhi','South West delhi','Vasant Vihar-1','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,110057,'Delhi','South West delhi','Vasant Vihar-2','cc_in');
