insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793011,'Meghalaya','East Khasi hills','Assam Rifles','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793106,'Meghalaya','East Khasi hills','Balat','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793107,'Meghalaya','East Khasi hills','Bholaganj Bazar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793004,'Meghalaya','East Khasi hills','Bishnupur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793111,'Meghalaya','East Khasi hills','Cherrabazar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793108,'Meghalaya','East Khasi hills','Cherrapunjee','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793112,'Meghalaya','East Khasi hills','Dalia','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793109,'Meghalaya','East Khasi hills','Dawki','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793106,'Meghalaya','East Khasi hills','Dholai','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793005,'Meghalaya','East Khasi hills','Diengiei','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793012,'Meghalaya','East Khasi hills','Diengpasoh','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793112,'Meghalaya','East Khasi hills','Disong','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793106,'Meghalaya','East Khasi hills','Gumaghat','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793007,'Meghalaya','East Khasi hills','Happy Valley','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793112,'Meghalaya','East Khasi hills','Ichamati','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793002,'Meghalaya','East Khasi hills','Iewduh','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793110,'Meghalaya','East Khasi hills','Iewmawiong','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793002,'Meghalaya','East Khasi hills','Jaiaw','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793015,'Meghalaya','East Khasi hills','Jongksha','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793112,'Meghalaya','East Khasi hills','Kalatak','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793015,'Meghalaya','East Khasi hills','Kharang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793106,'Meghalaya','East Khasi hills','Khonjoy','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793021,'Meghalaya','East Khasi hills','Kynton - u - mon','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793022,'Meghalaya','East Khasi hills','Kynton Massar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793004,'Meghalaya','East Khasi hills','Laban','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793111,'Meghalaya','East Khasi hills','Ladmawphlang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793111,'Meghalaya','East Khasi hills','Laitduh','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793010,'Meghalaya','East Khasi hills','Laitkor','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793010,'Meghalaya','East Khasi hills','Laitkor Peak','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793108,'Meghalaya','East Khasi hills','Laitkynsew','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793110,'Meghalaya','East Khasi hills','Laitlyngkot','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793111,'Meghalaya','East Khasi hills','Laitryngew','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793003,'Meghalaya','East Khasi hills','Laitumkhrah','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793110,'Meghalaya','East Khasi hills','Langkyrdem','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793113,'Meghalaya','East Khasi hills','Lawbah','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793004,'Meghalaya','East Khasi hills','Lawsohtun','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793121,'Meghalaya','East Khasi hills','Lyngiong','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793015,'Meghalaya','East Khasi hills','Lynshing','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793121,'Meghalaya','East Khasi hills','Madan Bitaw','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793021,'Meghalaya','East Khasi hills','Madanriting','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793108,'Meghalaya','East Khasi hills','Mahadeo','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793106,'Meghalaya','East Khasi hills','Makali','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793121,'Meghalaya','East Khasi hills','Marbisu','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793110,'Meghalaya','East Khasi hills','Mawbeh','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793108,'Meghalaya','East Khasi hills','Mawblang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793113,'Meghalaya','East Khasi hills','Mawdongbazar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793113,'Meghalaya','East Khasi hills','Mawhiang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793016,'Meghalaya','East Khasi hills','Mawiong','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793111,'Meghalaya','East Khasi hills','Mawkdok','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793012,'Meghalaya','East Khasi hills','Mawkhanu','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793009,'Meghalaya','East Khasi hills','Mawklot','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793121,'Meghalaya','East Khasi hills','Mawkriah','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793015,'Meghalaya','East Khasi hills','Mawkynrew','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793017,'Meghalaya','East Khasi hills','Mawlai','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793015,'Meghalaya','East Khasi hills','Mawlat','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793015,'Meghalaya','East Khasi hills','Mawlong','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793015,'Meghalaya','East Khasi hills','Mawlyngngad','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793108,'Meghalaya','East Khasi hills','Mawmluh','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793121,'Meghalaya','East Khasi hills','Mawngap','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793012,'Meghalaya','East Khasi hills','Mawpat','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793121,'Meghalaya','East Khasi hills','Mawphlang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793121,'Meghalaya','East Khasi hills','Mawpun','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793106,'Meghalaya','East Khasi hills','Mawput','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793121,'Meghalaya','East Khasi hills','Mawreng','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793008,'Meghalaya','East Khasi hills','Mawroh','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793021,'Meghalaya','East Khasi hills','Mawryngkneng','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793113,'Meghalaya','East Khasi hills','Mawsynram','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793022,'Meghalaya','East Khasi hills','Mawtawar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793001,'Meghalaya','East Khasi hills','Meghalaya Secretariat','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793106,'Meghalaya','East Khasi hills','Munai','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793110,'Meghalaya','East Khasi hills','Myllat','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793009,'Meghalaya','East Khasi hills','Mylliem Syllai u lar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793022,'Meghalaya','East Khasi hills','Nehu','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793018,'Meghalaya','East Khasi hills','Neigrihms','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793110,'Meghalaya','East Khasi hills','Nongjri','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793015,'Meghalaya','East Khasi hills','Nongkrem','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793110,'Meghalaya','East Khasi hills','Nongkynrih','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793009,'Meghalaya','East Khasi hills','Nonglyer','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793011,'Meghalaya','East Khasi hills','Nongmynsong','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793121,'Meghalaya','East Khasi hills','Nongspung','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793014,'Meghalaya','East Khasi hills','Nongthymmai','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793005,'Meghalaya','East Khasi hills','Nongumlong','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793001,'Meghalaya','East Khasi hills','Oakland','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793021,'Meghalaya','East Khasi hills','Pamora','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793113,'Meghalaya','East Khasi hills','Phlang Mawsyrpat','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793113,'Meghalaya','East Khasi hills','Phlangwanbroi','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793008,'Meghalaya','East Khasi hills','Phudmawri','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793010,'Meghalaya','East Khasi hills','Pomlakrai','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793121,'Meghalaya','East Khasi hills','Pongkung','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793021,'Meghalaya','East Khasi hills','Puriang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793106,'Meghalaya','East Khasi hills','Pyndeng Sohsaw','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793110,'Meghalaya','East Khasi hills','Pynursla','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793111,'Meghalaya','East Khasi hills','Ramdait','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793121,'Meghalaya','East Khasi hills','Rangshken','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793004,'Meghalaya','East Khasi hills','Rilbong','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793015,'Meghalaya','East Khasi hills','Ryngibah','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793113,'Meghalaya','East Khasi hills','Ryngkubazar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793006,'Meghalaya','East Khasi hills','Rynjah','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793112,'Meghalaya','East Khasi hills','Shella','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793001,'Meghalaya','East Khasi hills','Shillong.','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793015,'Meghalaya','East Khasi hills','Smit','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793108,'Meghalaya','East Khasi hills','Sohbarpunjee','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793121,'Meghalaya','East Khasi hills','Sohiong','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793108,'Meghalaya','East Khasi hills','Sohkmie','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793121,'Meghalaya','East Khasi hills','Sohpian','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793015,'Meghalaya','East Khasi hills','Sohryngkham','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793106,'Meghalaya','East Khasi hills','Sonatola','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793104,'Meghalaya','East Khasi hills','Sumer','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793113,'Meghalaya','East Khasi hills','Syntein','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793106,'Meghalaya','East Khasi hills','Telsora','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793015,'Meghalaya','East Khasi hills','Thangsning','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793113,'Meghalaya','East Khasi hills','Thyllaw','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793015,'Meghalaya','East Khasi hills','Thynroit','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793106,'Meghalaya','East Khasi hills','Trangpleng','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793113,'Meghalaya','East Khasi hills','Tynger','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793012,'Meghalaya','East Khasi hills','Tynring','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793111,'Meghalaya','East Khasi hills','Tynrong','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793108,'Meghalaya','East Khasi hills','Tyrna','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793121,'Meghalaya','East Khasi hills','Tyrsad','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793006,'Meghalaya','East Khasi hills','Umkdait','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793110,'Meghalaya','East Khasi hills','Umniuh - tmar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793015,'Meghalaya','East Khasi hills','Umphyrnai','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793015,'Meghalaya','East Khasi hills','Umsning','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793109,'Meghalaya','East Khasi hills','Umsyiem','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793005,'Meghalaya','East Khasi hills','Upper Shillong','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793109,'Meghalaya','East Khasi hills','Wahkdait','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793108,'Meghalaya','East Khasi hills','Wahlong','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793110,'Meghalaya','East Khasi hills','Wahshiarkhmut','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793121,'Meghalaya','East Khasi hills','Weiloi','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793106,'Meghalaya','West Khasi hills','Borsora','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793119,'Meghalaya','West Khasi hills','Byrki','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793120,'Meghalaya','West Khasi hills','Dungki - ingdong','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793120,'Meghalaya','West Khasi hills','Iewmaroid','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793119,'Meghalaya','West Khasi hills','Jaidoh','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793114,'Meghalaya','West Khasi hills','Jakrem','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793114,'Meghalaya','West Khasi hills','Jashier','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793120,'Meghalaya','West Khasi hills','Khlieh Lyngkhoi','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793119,'Meghalaya','West Khasi hills','Khliehmawlieh','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793120,'Meghalaya','West Khasi hills','Kynrut','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793120,'Meghalaya','West Khasi hills','Kynshi','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793120,'Meghalaya','West Khasi hills','Laitdombah','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793119,'Meghalaya','West Khasi hills','Laitkseh','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793114,'Meghalaya','West Khasi hills','Laitnongrim','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793119,'Meghalaya','West Khasi hills','Langdongdai','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793120,'Meghalaya','West Khasi hills','Langtor','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793120,'Meghalaya','West Khasi hills','Lawbyrtun','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793120,'Meghalaya','West Khasi hills','Lyngkhoi','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793120,'Meghalaya','West Khasi hills','Madanbynther','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793120,'Meghalaya','West Khasi hills','Mairang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793120,'Meghalaya','West Khasi hills','Manai','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793119,'Meghalaya','West Khasi hills','Marskuin','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793119,'Meghalaya','West Khasi hills','Maweitlyngngam','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793120,'Meghalaya','West Khasi hills','Mawkarah','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793119,'Meghalaya','West Khasi hills','Mawkohngei','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793114,'Meghalaya','West Khasi hills','Mawkyrwat','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793119,'Meghalaya','West Khasi hills','Mawlieh','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793114,'Meghalaya','West Khasi hills','Mawlyngwir','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793114,'Meghalaya','West Khasi hills','Mawsaw','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793120,'Meghalaya','West Khasi hills','Mawshut','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793114,'Meghalaya','West Khasi hills','Mawten','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793114,'Meghalaya','West Khasi hills','Mawthapdoh','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793119,'Meghalaya','West Khasi hills','Mawthengkut','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793119,'Meghalaya','West Khasi hills','Mawthungkper','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793121,'Meghalaya','West Khasi hills','Mawtiehbah','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793120,'Meghalaya','West Khasi hills','Myriaw','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793114,'Meghalaya','West Khasi hills','Ngunraw','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793119,'Meghalaya','West Khasi hills','Nongbah','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793119,'Meghalaya','West Khasi hills','Nongkasen','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793120,'Meghalaya','West Khasi hills','Nongkhlaw','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793119,'Meghalaya','West Khasi hills','Nonglang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793106,'Meghalaya','West Khasi hills','Nongnah','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793119,'Meghalaya','West Khasi hills','Nongpyndeng','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793119,'Meghalaya','West Khasi hills','Nongsdad dkhar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793119,'Meghalaya','West Khasi hills','Nongshyrkon','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793119,'Meghalaya','West Khasi hills','Nongstoin','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793114,'Meghalaya','West Khasi hills','Nongsynrih','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793120,'Meghalaya','West Khasi hills','Nongthliew','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793119,'Meghalaya','West Khasi hills','Nongthynniew','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793120,'Meghalaya','West Khasi hills','Nongum','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793119,'Meghalaya','West Khasi hills','Pam Briew','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793120,'Meghalaya','West Khasi hills','Pariong','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793114,'Meghalaya','West Khasi hills','Phlang Kynshi','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793119,'Meghalaya','West Khasi hills','Phlangdiloin','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793114,'Meghalaya','West Khasi hills','Phudjaud','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793106,'Meghalaya','West Khasi hills','Puksora','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793114,'Meghalaya','West Khasi hills','Pyndemsakwang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793119,'Meghalaya','West Khasi hills','Pyndengrei','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793106,'Meghalaya','West Khasi hills','Rajapara','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793119,'Meghalaya','West Khasi hills','Rambrai','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793119,'Meghalaya','West Khasi hills','Rangblang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793114,'Meghalaya','West Khasi hills','Rangmaw','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793114,'Meghalaya','West Khasi hills','Rangthong','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793106,'Meghalaya','West Khasi hills','Ranikor','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793119,'Meghalaya','West Khasi hills','Riangdo Bazar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793106,'Meghalaya','West Khasi hills','Rongasora','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793106,'Meghalaya','West Khasi hills','Sarin','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793119,'Meghalaya','West Khasi hills','Seinduli Bazar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793119,'Meghalaya','West Khasi hills','Shallang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793114,'Meghalaya','West Khasi hills','Sngimawlein','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793119,'Meghalaya','West Khasi hills','Thangpylleng Pyndemkseh','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793120,'Meghalaya','West Khasi hills','Tihnongbah','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793119,'Meghalaya','West Khasi hills','Umdohlun','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793114,'Meghalaya','West Khasi hills','Umjarain','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793120,'Meghalaya','West Khasi hills','Umkrem','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793106,'Meghalaya','West Khasi hills','Umpung','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793119,'Meghalaya','West Khasi hills','Umsohpieng','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793120,'Meghalaya','West Khasi hills','Umthlong','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793119,'Meghalaya','West Khasi hills','Umyap','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793119,'Meghalaya','West Khasi hills','Wahkaji','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793104,'Meghalaya','Ri Bhoi','Barua Basti','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793103,'Meghalaya','Ri Bhoi','Bhoilymbong','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793101,'Meghalaya','Ri Bhoi','Byrnihat','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793101,'Meghalaya','Ri Bhoi','Epip Byrnihat','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793102,'Meghalaya','Ri Bhoi','Hatumling','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793101,'Meghalaya','Ri Bhoi','Jorabat','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793101,'Meghalaya','Ri Bhoi','Killing Centre','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793102,'Meghalaya','Ri Bhoi','Kynjoin Umran','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793103,'Meghalaya','Ri Bhoi','Kyrdem','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793105,'Meghalaya','Ri Bhoi','Kyrdem Kulai','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793102,'Meghalaya','Ri Bhoi','Lailad','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793102,'Meghalaya','Ri Bhoi','Marmain','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793102,'Meghalaya','Ri Bhoi','Marngar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793103,'Meghalaya','Ri Bhoi','Mawbri','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793105,'Meghalaya','Ri Bhoi','Mawhati','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793103,'Meghalaya','Ri Bhoi','Mawlasnai','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793102,'Meghalaya','Ri Bhoi','Mawlong','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793105,'Meghalaya','Ri Bhoi','Mawrong','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793102,'Meghalaya','Ri Bhoi','Niangbari','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793102,'Meghalaya','Ri Bhoi','Nongladew','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793102,'Meghalaya','Ri Bhoi','Nongpoh','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793103,'Meghalaya','Ri Bhoi','Rongmen','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793102,'Meghalaya','Ri Bhoi','Saiden','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793105,'Meghalaya','Ri Bhoi','Sanidon','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793101,'Meghalaya','Ri Bhoi','Tamul Kuchi gaon','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793122,'Meghalaya','Ri Bhoi','Ucc','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793102,'Meghalaya','Ri Bhoi','Umden','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793102,'Meghalaya','Ri Bhoi','Umdihar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793103,'Meghalaya','Ri Bhoi','Umiam','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793103,'Meghalaya','Ri Bhoi','Umktieh','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793105,'Meghalaya','Ri Bhoi','Umran','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793102,'Meghalaya','Ri Bhoi','Umrit','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793103,'Meghalaya','Ri Bhoi','Umroi','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793123,'Meghalaya','Ri Bhoi','Umsaw','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793102,'Meghalaya','Ri Bhoi','Umsawnongbri','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793102,'Meghalaya','Ri Bhoi','Umshakhon Mathon','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793105,'Meghalaya','Ri Bhoi','Umsning','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793105,'Meghalaya','Ri Bhoi','Umsohlait','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794002,'Meghalaya','West Garo hills','Achigchonggiri','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794115,'Meghalaya','West Garo hills','Ampati','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794002,'Meghalaya','West Garo hills','Anugiri','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794101,'Meghalaya','West Garo hills','Araimile','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794002,'Meghalaya','West Garo hills','Bajengdoba','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794106,'Meghalaya','West Garo hills','Balunghat','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794115,'Meghalaya','West Garo hills','Bandelkona','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794103,'Meghalaya','West Garo hills','Barengapara','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794104,'Meghalaya','West Garo hills','Batabari','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794109,'Meghalaya','West Garo hills','Belguri','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794115,'Meghalaya','West Garo hills','Betsing','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794104,'Meghalaya','West Garo hills','Bhaitbari','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794104,'Meghalaya','West Garo hills','Bhajamara','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794104,'Meghalaya','West Garo hills','Bholarbhita','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794109,'Meghalaya','West Garo hills','Bolangitak','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794005,'Meghalaya','West Garo hills','Bolchugre','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794109,'Meghalaya','West Garo hills','Borjhora','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794101,'Meghalaya','West Garo hills','Captain Reserve','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794103,'Meghalaya','West Garo hills','Chandabhui','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794106,'Meghalaya','West Garo hills','Chapahati','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794103,'Meghalaya','West Garo hills','Chati','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794103,'Meghalaya','West Garo hills','Chengapara','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794005,'Meghalaya','West Garo hills','Chokpotgiri','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794104,'Meghalaya','West Garo hills','Dadengiri','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794002,'Meghalaya','West Garo hills','Dajongpara','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794101,'Meghalaya','West Garo hills','Dakopgiri','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794105,'Meghalaya','West Garo hills','Damalgiri','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794005,'Meghalaya','West Garo hills','Dekubazar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794005,'Meghalaya','West Garo hills','Dhopgiri','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794103,'Meghalaya','West Garo hills','Dimapara','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794005,'Meghalaya','West Garo hills','Dobasipara','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794002,'Meghalaya','West Garo hills','Edenbari Rongkhon','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794104,'Meghalaya','West Garo hills','Fulbari','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794002,'Meghalaya','West Garo hills','Gabil','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794103,'Meghalaya','West Garo hills','Gachuapara','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794005,'Meghalaya','West Garo hills','Gambigre','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794103,'Meghalaya','West Garo hills','Ganchudari','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794105,'Meghalaya','West Garo hills','Garobadha','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794105,'Meghalaya','West Garo hills','Garodoba','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794104,'Meghalaya','West Garo hills','Gatsingbazar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794005,'Meghalaya','West Garo hills','Gongrengiri','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794106,'Meghalaya','West Garo hills','Gopinath Killa','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794105,'Meghalaya','West Garo hills','Grenggandi Agal','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794104,'Meghalaya','West Garo hills','Gumaijhora','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794105,'Meghalaya','West Garo hills','Haldibari','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794109,'Meghalaya','West Garo hills','Halloidanga','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794104,'Meghalaya','West Garo hills','Haripur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794109,'Meghalaya','West Garo hills','Hatugaon','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794104,'Meghalaya','West Garo hills','Holidayganj','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794109,'Meghalaya','West Garo hills','Jengrapara','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794002,'Meghalaya','West Garo hills','Jingjal','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794103,'Meghalaya','West Garo hills','Joshipara','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794115,'Meghalaya','West Garo hills','Kalaichar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794106,'Meghalaya','West Garo hills','Kalaipara','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794105,'Meghalaya','West Garo hills','Kalchengapara','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794103,'Meghalaya','West Garo hills','Kapasipara','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794115,'Meghalaya','West Garo hills','Katuli','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794106,'Meghalaya','West Garo hills','Kawahagra','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794103,'Meghalaya','West Garo hills','Kharapara','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794103,'Meghalaya','West Garo hills','Killapara','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794002,'Meghalaya','West Garo hills','Lower Chandmari','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794106,'Meghalaya','West Garo hills','Mahendraganj','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794106,'Meghalaya','West Garo hills','Majerchar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794104,'Meghalaya','West Garo hills','Manlakandi','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794002,'Meghalaya','West Garo hills','Matchakgiri','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794104,'Meghalaya','West Garo hills','Mechanpani','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794105,'Meghalaya','West Garo hills','Melliam','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794002,'Meghalaya','West Garo hills','Mendal','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794112,'Meghalaya','West Garo hills','Mendipathar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794103,'Meghalaya','West Garo hills','Mihanpara','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794105,'Meghalaya','West Garo hills','Monobari','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794105,'Meghalaya','West Garo hills','Mukhdangra','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794107,'Meghalaya','West Garo hills','Nangwalbibra','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794104,'Meghalaya','West Garo hills','New Bhaitbari','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794106,'Meghalaya','West Garo hills','Nogorpara','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794105,'Meghalaya','West Garo hills','Okkapara','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794104,'Meghalaya','West Garo hills','Paham','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794109,'Meghalaya','West Garo hills','Pedaldoba','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794109,'Meghalaya','West Garo hills','Photamati','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794103,'Meghalaya','West Garo hills','Purakhasia','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794002,'Meghalaya','West Garo hills','Raja Apal','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794104,'Meghalaya','West Garo hills','Rajabala','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794109,'Meghalaya','West Garo hills','Raksamgiri','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794002,'Meghalaya','West Garo hills','Raribazar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794108,'Meghalaya','West Garo hills','Resubelpara','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794103,'Meghalaya','West Garo hills','Rimrangapara','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794104,'Meghalaya','West Garo hills','Rombazar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794002,'Meghalaya','West Garo hills','Rongkhon','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794104,'Meghalaya','West Garo hills','Rongmatchokgiri','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794002,'Meghalaya','West Garo hills','Rongram','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794105,'Meghalaya','West Garo hills','Rongsakhona','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794104,'Meghalaya','West Garo hills','Sabribari','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794115,'Meghalaya','West Garo hills','Salmanpara','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794103,'Meghalaya','West Garo hills','Sasengpara','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794105,'Meghalaya','West Garo hills','Selsella','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794005,'Meghalaya','West Garo hills','Shankinigiri','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794104,'Meghalaya','West Garo hills','Shyamnagar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794103,'Meghalaya','West Garo hills','Sibbari','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794103,'Meghalaya','West Garo hills','Silkhigiri','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794115,'Meghalaya','West Garo hills','Sulgre','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794105,'Meghalaya','West Garo hills','Teporpara','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794109,'Meghalaya','West Garo hills','Tikrikilla','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794001,'Meghalaya','West Garo hills','Tura','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794105,'Meghalaya','West Garo hills','Zekabari','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794115,'Meghalaya','West Garo hills','Zigzak','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794102,'Meghalaya','South Garo hills','Baghmara','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794102,'Meghalaya','South Garo hills','Balkhalbazar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794102,'Meghalaya','South Garo hills','Balsalgiri','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794114,'Meghalaya','South Garo hills','Dambuk Agal','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794102,'Meghalaya','South Garo hills','Emangiri','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794114,'Meghalaya','South Garo hills','Mahesh Khola','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794102,'Meghalaya','South Garo hills','Mendikgiri','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794102,'Meghalaya','South Garo hills','Nilwalgiri','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794102,'Meghalaya','South Garo hills','Panda','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794114,'Meghalaya','South Garo hills','Rongra','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794102,'Meghalaya','South Garo hills','Siju','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794114,'Meghalaya','South Garo hills','Warimagiri','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793150,'Meghalaya','Jaintia Hills','Amlarem','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793109,'Meghalaya','Jaintia Hills','Amlari','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793150,'Meghalaya','Jaintia Hills','Barato','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793160,'Meghalaya','Jaintia Hills','Bataw','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793109,'Meghalaya','Jaintia Hills','Darrang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793200,'Meghalaya','Jaintia Hills','Huroi','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793150,'Meghalaya','Jaintia Hills','Iawthymmai','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793150,'Meghalaya','Jaintia Hills','Jarain','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793150,'Meghalaya','Jaintia Hills','Jowai','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793151,'Meghalaya','Jaintia Hills','Khanduli','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793200,'Meghalaya','Jaintia Hills','Khatum','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793200,'Meghalaya','Jaintia Hills','Khliehriat','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793150,'Meghalaya','Jaintia Hills','Kyndong Tuber','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793160,'Meghalaya','Jaintia Hills','Ladrymbai','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793109,'Meghalaya','Jaintia Hills','Lamin','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793150,'Meghalaya','Jaintia Hills','Laskein','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793200,'Meghalaya','Jaintia Hills','Lumshnong','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793109,'Meghalaya','Jaintia Hills','Lyngkhat','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793151,'Meghalaya','Jaintia Hills','Mawbakhon','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793151,'Meghalaya','Jaintia Hills','Mawdymmai','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793150,'Meghalaya','Jaintia Hills','Mawkaiaw','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793150,'Meghalaya','Jaintia Hills','Mawkyndeng','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793150,'Meghalaya','Jaintia Hills','Mihmyntdu','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793151,'Meghalaya','Jaintia Hills','Mookynniang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793160,'Meghalaya','Jaintia Hills','Mukhialong','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793109,'Meghalaya','Jaintia Hills','Muktapur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793150,'Meghalaya','Jaintia Hills','Mupyut','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793160,'Meghalaya','Jaintia Hills','Musniang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793150,'Meghalaya','Jaintia Hills','Mustem','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793200,'Meghalaya','Jaintia Hills','Myndihati','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793150,'Meghalaya','Jaintia Hills','Mynso','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793109,'Meghalaya','Jaintia Hills','Naljuri','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793151,'Meghalaya','Jaintia Hills','Namdong','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793151,'Meghalaya','Jaintia Hills','Nartiang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793150,'Meghalaya','Jaintia Hills','Nongbah','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793109,'Meghalaya','Jaintia Hills','Nongbareh','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793151,'Meghalaya','Jaintia Hills','Nongjngi','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793150,'Meghalaya','Jaintia Hills','Nongryngkoh','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793109,'Meghalaya','Jaintia Hills','Nongtalang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793109,'Meghalaya','Jaintia Hills','Nongtyngur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793109,'Meghalaya','Jaintia Hills','Padu','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793200,'Meghalaya','Jaintia Hills','Pala','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793109,'Meghalaya','Jaintia Hills','Pamshutia','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793109,'Meghalaya','Jaintia Hills','Passadwar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793150,'Meghalaya','Jaintia Hills','Pdengshakap','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793109,'Meghalaya','Jaintia Hills','Pongtung','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793150,'Meghalaya','Jaintia Hills','Raliang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793200,'Meghalaya','Jaintia Hills','Rata Cherra','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793109,'Meghalaya','Jaintia Hills','Rongkhum','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793160,'Meghalaya','Jaintia Hills','Rymbai','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793150,'Meghalaya','Jaintia Hills','Sahsniang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793200,'Meghalaya','Jaintia Hills','Saipung','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793151,'Meghalaya','Jaintia Hills','Saitsama','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793160,'Meghalaya','Jaintia Hills','Sham Sham','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793150,'Meghalaya','Jaintia Hills','Shangpung','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793200,'Meghalaya','Jaintia Hills','Sheruphie','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793200,'Meghalaya','Jaintia Hills','Shnongrim','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793109,'Meghalaya','Jaintia Hills','Sohkha','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793160,'Meghalaya','Jaintia Hills','Sohkymphor','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793150,'Meghalaya','Jaintia Hills','Sohmynting','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793200,'Meghalaya','Jaintia Hills','Sonapur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793200,'Meghalaya','Jaintia Hills','Sutnga','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793109,'Meghalaya','Jaintia Hills','Syndai','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793151,'Meghalaya','Jaintia Hills','Thadlaskein','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793150,'Meghalaya','Jaintia Hills','Thadmuthlong','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793150,'Meghalaya','Jaintia Hills','Thangbuli','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793150,'Meghalaya','Jaintia Hills','Thangrain','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793150,'Meghalaya','Jaintia Hills','Trangblang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793160,'Meghalaya','Jaintia Hills','Tuber Kmaishnong','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793200,'Meghalaya','Jaintia Hills','Umkiang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793151,'Meghalaya','Jaintia Hills','Umladang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793151,'Meghalaya','Jaintia Hills','Ummulong','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793151,'Meghalaya','Jaintia Hills','Wahiajer','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793160,'Meghalaya','Jaintia Hills','Wapung','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793150,'Meghalaya','Jaintia Hills','Yalang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,793150,'Meghalaya','Jaintia Hills','Yooksi','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794111,'Meghalaya','East Garo hills','Balkinigiri','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794110,'Meghalaya','East Garo hills','Dabu','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794108,'Meghalaya','East Garo hills','Dagal','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794110,'Meghalaya','East Garo hills','Dainadubi','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794108,'Meghalaya','East Garo hills','Daram','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794110,'Meghalaya','East Garo hills','Darugiri','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794110,'Meghalaya','East Garo hills','Dokangsi','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794110,'Meghalaya','East Garo hills','Gairong','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794110,'Meghalaya','East Garo hills','Gambil','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794108,'Meghalaya','East Garo hills','Haluapara','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794107,'Meghalaya','East Garo hills','Jadigitim','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794110,'Meghalaya','East Garo hills','Mangsang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794110,'Meghalaya','East Garo hills','Nongcharan','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794111,'Meghalaya','East Garo hills','Rombagiri','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794110,'Meghalaya','East Garo hills','Ronga Agal','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794110,'Meghalaya','East Garo hills','Rongchek Akhong','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794110,'Meghalaya','East Garo hills','Rongjeng','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794110,'Meghalaya','East Garo hills','Rongmil','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794111,'Meghalaya','East Garo hills','Rongrengiri','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794108,'Meghalaya','East Garo hills','Rongrong','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794111,'Meghalaya','East Garo hills','Rongsakgiri','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794111,'Meghalaya','East Garo hills','Sakhadongiri','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794111,'Meghalaya','East Garo hills','Samanda','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794111,'Meghalaya','East Garo hills','Songsak','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794108,'Meghalaya','East Garo hills','Thapa','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794110,'Meghalaya','East Garo hills','Wagachi','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,794111,'Meghalaya','East Garo hills','Williamnagar','cc_in');
