insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797100,'Nagaland','Wokha','Aitepyong','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797111,'Nagaland','Wokha','Baghty','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797111,'Nagaland','Wokha','Bhandari','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797111,'Nagaland','Wokha','Chukitong','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797100,'Nagaland','Wokha','Doyang Hydel project','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797111,'Nagaland','Wokha','Elumnyu','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797111,'Nagaland','Wokha','Englan','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797111,'Nagaland','Wokha','Humtsu','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797100,'Nagaland','Wokha','Longtsung','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797100,'Nagaland','Wokha','Lotsu','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797111,'Nagaland','Wokha','Mekhukla','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797100,'Nagaland','Wokha','Moilan','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797111,'Nagaland','Wokha','N. longidong','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797111,'Nagaland','Wokha','Nyiro','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797100,'Nagaland','Wokha','Pangti','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797111,'Nagaland','Wokha','Pongitong','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797100,'Nagaland','Wokha','Sanis','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797100,'Nagaland','Wokha','Sungro','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797111,'Nagaland','Wokha','Tsungtsutong','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797111,'Nagaland','Wokha','Wokha','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797111,'Nagaland','Wokha','Wokha Village','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797111,'Nagaland','Wokha','Wozhru','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797100,'Nagaland','Wokha','Yamhon','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797111,'Nagaland','Wokha','Yikhum','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797109,'Nagaland','Kohima','Asukika','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797105,'Nagaland','Kohima','Botsa','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797003,'Nagaland','Kohima','Chakhabama','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797109,'Nagaland','Kohima','Chatashi','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797003,'Nagaland','Kohima','Chedema','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797105,'Nagaland','Kohima','Chiechama','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797105,'Nagaland','Kohima','Chiephobozou','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797003,'Nagaland','Kohima','Ciesema','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797003,'Nagaland','Kohima','Dihoma','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797109,'Nagaland','Kohima','Ghathashi','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797005,'Nagaland','Kohima','Jakhama','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797002,'Nagaland','Kohima','Jotsoma','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797003,'Nagaland','Kohima','Kedima','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797002,'Nagaland','Kohima','Khonoma','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797005,'Nagaland','Kohima','Khuzama','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797005,'Nagaland','Kohima','Kigwema','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797003,'Nagaland','Kohima','Kizocha','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797001,'Nagaland','Kohima','Kohima','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797005,'Nagaland','Kohima','Kohima Pwd','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797002,'Nagaland','Kohima','Kohima Science college','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797003,'Nagaland','Kohima','Kohima Village','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797109,'Nagaland','Kohima','Kontsunyu','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797005,'Nagaland','Kohima','Lalmati','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797109,'Nagaland','Kohima','Lazami','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797002,'Nagaland','Kohima','Mezoma','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797005,'Nagaland','Kohima','Mima','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797105,'Nagaland','Kohima','Mishilimi','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797001,'Nagaland','Kohima','Monkhola','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797004,'Nagaland','Kohima','N.E.h.u.','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797004,'Nagaland','Kohima','New Sectt complex','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797109,'Nagaland','Kohima','Nisenyu','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797109,'Nagaland','Kohima','Nyishunyu','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797109,'Nagaland','Kohima','Phenshunyu','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797109,'Nagaland','Kohima','Phenwhenyu','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797005,'Nagaland','Kohima','Phesama','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797002,'Nagaland','Kohima','Poilwa','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797109,'Nagaland','Kohima','Pughoboto','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797003,'Nagaland','Kohima','Rusoma','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797109,'Nagaland','Kohima','Sendenyu','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797109,'Nagaland','Kohima','Tesophenyu','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797004,'Nagaland','Kohima','Thizama','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797109,'Nagaland','Kohima','Tseminyu','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797109,'Nagaland','Kohima','Tseminyu Old town','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797109,'Nagaland','Kohima','Tsosesunyu','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797105,'Nagaland','Kohima','Tuophema','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797005,'Nagaland','Kohima','Viswema','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797109,'Nagaland','Kohima','Zephenyu','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797105,'Nagaland','Kohima','Zhadima','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797005,'Nagaland','Kohima','Zubza','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797110,'Nagaland','Peren','Athibung','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797110,'Nagaland','Peren','Bongkholong','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797110,'Nagaland','Peren','Gaili','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797110,'Nagaland','Peren','Jalukie 'b'','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797110,'Nagaland','Peren','Khelma','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797110,'Nagaland','Peren','Lilen','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797101,'Nagaland','Peren','Mbaulwa','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797110,'Nagaland','Peren','Mhainamtsi','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797101,'Nagaland','Peren','N.Song','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797101,'Nagaland','Peren','Nchongram','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797110,'Nagaland','Peren','New Jalukie','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797101,'Nagaland','Peren','Peren','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797110,'Nagaland','Peren','Samjiuram','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797101,'Nagaland','Peren','Tening','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797110,'Nagaland','Peren','Zalukie','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798611,'Nagaland','Kiphire','Amahatore','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798611,'Nagaland','Kiphire','Anatongere','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798611,'Nagaland','Kiphire','Kiphire','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798611,'Nagaland','Kiphire','Kisethong','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798611,'Nagaland','Kiphire','Longmatra','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798611,'Nagaland','Kiphire','Moya','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798611,'Nagaland','Kiphire','Phalonger','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798611,'Nagaland','Kiphire','Pokhpur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798611,'Nagaland','Kiphire','Pungro','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798611,'Nagaland','Kiphire','Seyochang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798611,'Nagaland','Kiphire','Sikur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798611,'Nagaland','Kiphire','Singrup','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798611,'Nagaland','Kiphire','Sitimi','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797114,'Nagaland','Phek','Akhegwo','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797104,'Nagaland','Phek','Chetheba','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797102,'Nagaland','Phek','Chizami','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797102,'Nagaland','Phek','Chizami Village','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797104,'Nagaland','Phek','Chozuba','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797104,'Nagaland','Phek','Dzulhami','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797114,'Nagaland','Phek','Hutsu','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797108,'Nagaland','Phek','Ketsapo','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797107,'Nagaland','Phek','Khezhakeno','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797108,'Nagaland','Phek','Khuzami','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797107,'Nagaland','Phek','Kikruma','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797104,'Nagaland','Phek','Kilomi','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797114,'Nagaland','Phek','Lephori','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797108,'Nagaland','Phek','Losami','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797108,'Nagaland','Phek','Luzaphuhu','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797114,'Nagaland','Phek','Meluri','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797107,'Nagaland','Phek','Mesolumi','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797102,'Nagaland','Phek','Middle Khomi','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797108,'Nagaland','Phek','Old Phek','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797107,'Nagaland','Phek','Pfutsero','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797108,'Nagaland','Phek','Phek','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797107,'Nagaland','Phek','Phesachuduma','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797104,'Nagaland','Phek','Phugwu','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797107,'Nagaland','Phek','Porba','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797114,'Nagaland','Phek','Pungkhuri','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797104,'Nagaland','Phek','Runguzumi','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797107,'Nagaland','Phek','Sakraba','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797107,'Nagaland','Phek','Tekhouba','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797102,'Nagaland','Phek','Thechulumi','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797104,'Nagaland','Phek','Thenizumi','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797107,'Nagaland','Phek','Thipuzumi','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797104,'Nagaland','Phek','Thvophisumi','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797114,'Nagaland','Phek','Wazhiho','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797104,'Nagaland','Phek','Yaribami','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797107,'Nagaland','Phek','Zaketsa','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797107,'Nagaland','Phek','Zavame','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797107,'Nagaland','Phek','Zhamai','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798603,'Nagaland','Mon','Angphang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798622,'Nagaland','Mon','Baranamsang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798603,'Nagaland','Mon','Champang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798603,'Nagaland','Mon','Chengloisho','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798603,'Nagaland','Mon','Chenwetnyu','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798603,'Nagaland','Mon','Chingkao','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798603,'Nagaland','Mon','Chinglong','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798621,'Nagaland','Mon','Chui','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798603,'Nagaland','Mon','Jakpang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798622,'Nagaland','Mon','Kongon','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798603,'Nagaland','Mon','Longching','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798621,'Nagaland','Mon','Longpong Senghe','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798621,'Nagaland','Mon','Longwa','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798621,'Nagaland','Mon','Mon','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798603,'Nagaland','Mon','Monyakshu','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798622,'Nagaland','Mon','Naginimora','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798602,'Nagaland','Mon','Namsa','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798603,'Nagaland','Mon','Pessao','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798621,'Nagaland','Mon','Pongkong','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798621,'Nagaland','Mon','Singha Chingnyu','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798621,'Nagaland','Mon','Tang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798602,'Nagaland','Mon','Tizit','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798603,'Nagaland','Mon','Tobu','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798621,'Nagaland','Mon','Totak','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798603,'Nagaland','Mon','Ukha','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798622,'Nagaland','Mon','Wakching','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798621,'Nagaland','Mon','Waunching','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798602,'Nagaland','Mon','Yannu','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798602,'Nagaland','Mon','Zaboka','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798602,'Nagaland','Mon','Zangkham','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798625,'Nagaland','Longleng','Hukpang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798625,'Nagaland','Longleng','Longleng','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798625,'Nagaland','Longleng','Nian','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798625,'Nagaland','Longleng','Phomching','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798625,'Nagaland','Longleng','Sakchi','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798625,'Nagaland','Longleng','Yachem','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798625,'Nagaland','Longleng','Yongyak','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797106,'Nagaland','Dimapur','Agri College','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797115,'Nagaland','Dimapur','Aoyimti','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797115,'Nagaland','Dimapur','Artc','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797103,'Nagaland','Dimapur','Chumukedima','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797117,'Nagaland','Dimapur','Circular Road','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797115,'Nagaland','Dimapur','Daroga Pathar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797112,'Nagaland','Dimapur','Dimapur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797116,'Nagaland','Dimapur','Dimapur Bazar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797115,'Nagaland','Dimapur','Diphupar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797112,'Nagaland','Dimapur','Doyapur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797113,'Nagaland','Dimapur','Duncan Basti','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797115,'Nagaland','Dimapur','Eralibill','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797112,'Nagaland','Dimapur','Hening Kunglwa','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797113,'Nagaland','Dimapur','Industrial Estate','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797112,'Nagaland','Dimapur','Jalukiekam','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797106,'Nagaland','Dimapur','Jharnapani','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797106,'Nagaland','Dimapur','Khaibung','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797116,'Nagaland','Dimapur','Khehekhu','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797112,'Nagaland','Dimapur','Khermahal','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797103,'Nagaland','Dimapur','Khopoanaula','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797112,'Nagaland','Dimapur','Kuda','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797116,'Nagaland','Dimapur','Kuhuboto','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797116,'Nagaland','Dimapur','Kushiabill','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797113,'Nagaland','Dimapur','Lengrijan','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797106,'Nagaland','Dimapur','Maova','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797106,'Nagaland','Dimapur','Medziphema','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797103,'Nagaland','Dimapur','Moaikam','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797106,'Nagaland','Dimapur','Molvom','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797113,'Nagaland','Dimapur','New Nepaligaon','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797103,'Nagaland','Dimapur','Nihekhu','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797113,'Nagaland','Dimapur','Nst Colony','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797112,'Nagaland','Dimapur','Nuiland','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797103,'Nagaland','Dimapur','P C college','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797116,'Nagaland','Dimapur','Padampukhuri','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797112,'Nagaland','Dimapur','Phaipijan','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797106,'Nagaland','Dimapur','Pherima','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797103,'Nagaland','Dimapur','Pimla','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797106,'Nagaland','Dimapur','Piphima','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797106,'Nagaland','Dimapur','Punglwa','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797117,'Nagaland','Dimapur','Pwd Colony','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797112,'Nagaland','Dimapur','Ralan','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797117,'Nagaland','Dimapur','Rangapahar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797112,'Nagaland','Dimapur','Razaphima','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797115,'Nagaland','Dimapur','Showba Old','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797117,'Nagaland','Dimapur','Singal Village','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797112,'Nagaland','Dimapur','Singrijan','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797106,'Nagaland','Dimapur','Sirhima','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797115,'Nagaland','Dimapur','Suger Mill','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797115,'Nagaland','Dimapur','Sukhovi','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797103,'Nagaland','Dimapur','Tenyiphe','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797117,'Nagaland','Dimapur','Thahekhu','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797116,'Nagaland','Dimapur','Vihokhu','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797112,'Nagaland','Dimapur','Yampha','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,797117,'Nagaland','Dimapur','Zeliangrong','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798620,'Nagaland','Zunhebotto','Aghunato','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798619,'Nagaland','Zunhebotto','Aizuto','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798619,'Nagaland','Zunhebotto','Akuhaito','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798619,'Nagaland','Zunhebotto','Akuluto','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798620,'Nagaland','Zunhebotto','Asukhomi','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798619,'Nagaland','Zunhebotto','Asukuto','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798620,'Nagaland','Zunhebotto','Asuto','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798620,'Nagaland','Zunhebotto','Hosephu','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798620,'Nagaland','Zunhebotto','Kichilimi','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798620,'Nagaland','Zunhebotto','Phisami','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798620,'Nagaland','Zunhebotto','Saghemi','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798620,'Nagaland','Zunhebotto','Satakha','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798620,'Nagaland','Zunhebotto','Satami','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798620,'Nagaland','Zunhebotto','Satoi','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798620,'Nagaland','Zunhebotto','Suruhuto','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798620,'Nagaland','Zunhebotto','Surumi','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798620,'Nagaland','Zunhebotto','Tokiye','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798620,'Nagaland','Zunhebotto','Zunheboto','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798616,'Nagaland','Tuensang','Angangba','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798612,'Nagaland','Tuensang','Chessore','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798616,'Nagaland','Tuensang','Chimonger','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798612,'Nagaland','Tuensang','Chingmei','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798626,'Nagaland','Tuensang','Choklangan','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798616,'Nagaland','Tuensang','Chungtore','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798612,'Nagaland','Tuensang','Huker','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798616,'Nagaland','Tuensang','Kongsang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798612,'Nagaland','Tuensang','Kuthur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798616,'Nagaland','Tuensang','Longkhim','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798626,'Nagaland','Tuensang','Nokhu','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798626,'Nagaland','Tuensang','Noklak','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798616,'Nagaland','Tuensang','Noksen','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798626,'Nagaland','Tuensang','Pangsha','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798612,'Nagaland','Tuensang','Panso','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798626,'Nagaland','Tuensang','Pessu','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798626,'Nagaland','Tuensang','Sanglao','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798612,'Nagaland','Tuensang','Sangsanyu','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798612,'Nagaland','Tuensang','Saramati','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798612,'Nagaland','Tuensang','Shamator','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798612,'Nagaland','Tuensang','Shampur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798612,'Nagaland','Tuensang','Shiponger','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798612,'Nagaland','Tuensang','Sotokur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798612,'Nagaland','Tuensang','Thonokhunyu','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798612,'Nagaland','Tuensang','Tuensang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798612,'Nagaland','Tuensang','Tuensang Village','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798616,'Nagaland','Tuensang','Yangli','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798601,'Nagaland','Mokokchung','Alichen','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798604,'Nagaland','Mokokchung','Alungkima','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798604,'Nagaland','Mokokchung','Alungtaki','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798601,'Nagaland','Mokokchung','Aolijen','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798601,'Nagaland','Mokokchung','Arree Old','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798618,'Nagaland','Mokokchung','Asangma','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798618,'Nagaland','Mokokchung','Barakangtsung','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798601,'Nagaland','Mokokchung','Changki','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798613,'Nagaland','Mokokchung','Chantongia','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798601,'Nagaland','Mokokchung','Chare','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798614,'Nagaland','Mokokchung','Chuchuyimlang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798601,'Nagaland','Mokokchung','Chungtia','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798604,'Nagaland','Mokokchung','Chungtia Yimsen','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798601,'Nagaland','Mokokchung','Fazl Ali college','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798615,'Nagaland','Mokokchung','Impur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798604,'Nagaland','Mokokchung','Khari','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798617,'Nagaland','Mokokchung','Khensa','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798615,'Nagaland','Mokokchung','Kubulong','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798601,'Nagaland','Mokokchung','Kubza','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798615,'Nagaland','Mokokchung','Longchang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798604,'Nagaland','Mokokchung','Longchem','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798601,'Nagaland','Mokokchung','Longkhum','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798614,'Nagaland','Mokokchung','Longkong','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798601,'Nagaland','Mokokchung','Longmisa','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798604,'Nagaland','Mokokchung','Longnak','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798601,'Nagaland','Mokokchung','Longsa','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798601,'Nagaland','Mokokchung','Lumami','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798618,'Nagaland','Mokokchung','Luyang Valley','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798601,'Nagaland','Mokokchung','Mangmentong','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798613,'Nagaland','Mokokchung','Merangkong','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798601,'Nagaland','Mokokchung','Mokokchung','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798618,'Nagaland','Mokokchung','Molungkhimong','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798618,'Nagaland','Mokokchung','Molungyimsen','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798604,'Nagaland','Mokokchung','Mongchen','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798604,'Nagaland','Mokokchung','Mongkholemba','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798614,'Nagaland','Mokokchung','Mongsenyimti','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798601,'Nagaland','Mokokchung','Nst Colony','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798617,'Nagaland','Mokokchung','Opangkong','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798623,'Nagaland','Mokokchung','Paper Nagar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798613,'Nagaland','Mokokchung','Phangsang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798601,'Nagaland','Mokokchung','S. e. colony','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798614,'Nagaland','Mokokchung','Salulamang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798615,'Nagaland','Mokokchung','Sungratsu','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798618,'Nagaland','Mokokchung','Tamlu','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798601,'Nagaland','Mokokchung','Tronger','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798618,'Nagaland','Mokokchung','Tuli','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798614,'Nagaland','Mokokchung','Ungar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798601,'Nagaland','Mokokchung','Ungma','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798601,'Nagaland','Mokokchung','V. k. town','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798618,'Nagaland','Mokokchung','Wamaken','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798604,'Nagaland','Mokokchung','Waromung','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798613,'Nagaland','Mokokchung','Yaongyimsen','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,798614,'Nagaland','Mokokchung','Yisemyong','cc_in');
