insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,673320,'Puducherry','Mahe','Naluthara','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,673333,'Puducherry','Mahe','Pallur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,605007,'Puducherry','Pondicherry','Abishegapakkam','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,605007,'Puducherry','Pondicherry','Ariyankuppam','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,605110,'Puducherry','Pondicherry','Arumbarthapuram','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,607402,'Puducherry','Pondicherry','Bahoor','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,605104,'Puducherry','Pondicherry','Bommayarpalayam','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,605001,'Puducherry','Pondicherry','Botanical Garden','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,605014,'Puducherry','Pondicherry','Calapet','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,607402,'Puducherry','Pondicherry','Courivinatham','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,605006,'Puducherry','Pondicherry','Dhanvantry Nagar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,605106,'Puducherry','Pondicherry','Embalam','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,605111,'Puducherry','Pondicherry','Irumbai','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,605106,'Puducherry','Pondicherry','Karayamputhur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,605007,'Puducherry','Pondicherry','Karikalambakkam','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,605106,'Puducherry','Pondicherry','Kariyamanikam','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,605106,'Puducherry','Pondicherry','Kijour','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,605014,'Puducherry','Pondicherry','Kilpudupattu','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,604301,'Puducherry','Pondicherry','Kilsirivi','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,607402,'Puducherry','Pondicherry','Kirumambakkam','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,605110,'Puducherry','Pondicherry','Korkadu','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,605104,'Puducherry','Pondicherry','Kottakuppam','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,605101,'Puducherry','Pondicherry','Kuilapalayam','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,605008,'Puducherry','Pondicherry','Lawspet','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,605105,'Puducherry','Pondicherry','Maducore','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,607402,'Puducherry','Pondicherry','Manamedu','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,607402,'Puducherry','Pondicherry','Manapeth','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,605106,'Puducherry','Pondicherry','Mandagapet','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,605110,'Puducherry','Pondicherry','Mangalam','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,605501,'Puducherry','Pondicherry','Mannadipattu','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,605101,'Puducherry','Pondicherry','Morattandi','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,605009,'Puducherry','Pondicherry','Mottoupalayam','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,605004,'Puducherry','Pondicherry','Mouroungapakkam','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,605009,'Puducherry','Pondicherry','Moutrepaleam','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,605004,'Puducherry','Pondicherry','Mudaliarpet','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,605003,'Puducherry','Pondicherry','Muthialpet','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,605501,'Puducherry','Pondicherry','Mutrampattu','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,605007,'Puducherry','Pondicherry','Nallavadu','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,605005,'Puducherry','Pondicherry','Nellithoppe','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,605106,'Puducherry','Pondicherry','Nettapakkam','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,605001,'Puducherry','Pondicherry','Odiensalai','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,605010,'Puducherry','Pondicherry','Ozhugarai','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,605012,'Puducherry','Pondicherry','Padmin nagar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,605106,'Puducherry','Pondicherry','Pakkam','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,673310,'Puducherry','Pondicherry','Pandakkal','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,605014,'Puducherry','Pondicherry','Pillaichavady','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,607402,'Puducherry','Pondicherry','Pillayarkuppam','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,605001,'Puducherry','Pondicherry','Pondicherry','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,605001,'Puducherry','Pondicherry','Pondicherry Bazaar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,605001,'Puducherry','Pondicherry','Pondicherry Courts','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,605001,'Puducherry','Pondicherry','Pondicherry North','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,605014,'Puducherry','Pondicherry','Pondicherry University','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,605007,'Puducherry','Pondicherry','Pooranankuppam','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,605111,'Puducherry','Pondicherry','Poothurai','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,605111,'Puducherry','Pondicherry','Rayapudupakkam','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,605010,'Puducherry','Pondicherry','Reddiyarpalayam','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,605013,'Puducherry','Pondicherry','Saram(py)','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,605111,'Puducherry','Pondicherry','Sedarapet','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,607402,'Puducherry','Pondicherry','Seliamedu','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,605501,'Puducherry','Pondicherry','Sellipet','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,605002,'Puducherry','Pondicherry','Sri Aurobindo ashram','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,605110,'Puducherry','Pondicherry','Sulthanpet','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,605009,'Puducherry','Pondicherry','Thattanchavady','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,605004,'Puducherry','Pondicherry','Thengaithittu','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,605007,'Puducherry','Pondicherry','Thimmanaickenpalayam','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,605501,'Puducherry','Pondicherry','Tirukkanur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,605501,'Puducherry','Pondicherry','Vadhanur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,605007,'Puducherry','Pondicherry','Veerampattinam','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,605011,'Puducherry','Pondicherry','Venkata Nagar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,605110,'Puducherry','Pondicherry','Villiyanur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,605009,'Puducherry','Pondicherry','Vimacoundinpaleam','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,605106,'Puducherry','Pondicherry','Viranam','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,533464,'Puducherry','Pondicherry','Yanam','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,609604,'Puducherry','Karaikal','Akkaraivattam','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,609601,'Puducherry','Karaikal','Ambagarathur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,609602,'Puducherry','Karaikal','Dharmapuram','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,609602,'Puducherry','Karaikal','Karaikal','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,609602,'Puducherry','Karaikal','Karaikal Bazaar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,609602,'Puducherry','Karaikal','Karaikal South','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,609605,'Puducherry','Karaikal','Karaikalmedu','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,609605,'Puducherry','Karaikal','Karaikoilpathu','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,609607,'Puducherry','Karaikal','Karukangudi','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,609609,'Puducherry','Karaikal','Kottuchery','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,609603,'Puducherry','Karaikal','Kurumbagaram','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,609602,'Puducherry','Karaikal','Madagadi','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,609603,'Puducherry','Karaikal','Melakasakudi','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,609601,'Puducherry','Karaikal','Nallambal','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,609603,'Puducherry','Karaikal','Nallathur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,609603,'Puducherry','Karaikal','Nedungadu','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,609604,'Puducherry','Karaikal','Neravy','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,609601,'Puducherry','Karaikal','Seithur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,609607,'Puducherry','Karaikal','Sellur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,609607,'Puducherry','Karaikal','Surakudi','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,609606,'Puducherry','Karaikal','T.R.pattinam south','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,609605,'Puducherry','Karaikal','Thalatheru','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,609606,'Puducherry','Karaikal','Tirumalairayanpattinam','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,609607,'Puducherry','Karaikal','Tirunallar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,609609,'Puducherry','Karaikal','Tiruvettakudi','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,609609,'Puducherry','Karaikal','Varichikudi','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,609607,'Puducherry','Karaikal','Vizhithiyur','cc_in');
