insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737135,'Sikkim','East Sikkim','Ahoo Busty','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737133,'Sikkim','East Sikkim','Amba','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737133,'Sikkim','East Sikkim','Aritar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737135,'Sikkim','East Sikkim','Assam Lingzey','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737134,'Sikkim','East Sikkim','Bardang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737106,'Sikkim','East Sikkim','Bering','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737134,'Sikkim','East Sikkim','Bermiok','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737134,'Sikkim','East Sikkim','Beyong','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737103,'Sikkim','East Sikkim','Bhusuk','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737103,'Sikkim','East Sikkim','Bojoghari','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737106,'Sikkim','East Sikkim','Changayshanti','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737131,'Sikkim','East Sikkim','Chujachen','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737131,'Sikkim','East Sikkim','Dalapchand','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737102,'Sikkim','East Sikkim','Deorali','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737102,'Sikkim','East Sikkim','Dhajey','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737107,'Sikkim','East Sikkim','Dikchu','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737134,'Sikkim','East Sikkim','Dipudara Nhpc complex','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737132,'Sikkim','East Sikkim','Duga','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737132,'Sikkim','East Sikkim','East Pendam','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737134,'Sikkim','East Sikkim','Gangkha Busty','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737101,'Sikkim','East Sikkim','Gangtok','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737101,'Sikkim','East Sikkim','Gangtok Bazar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737102,'Sikkim','East Sikkim','Gnathang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737107,'Sikkim','East Sikkim','Gor','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737106,'Sikkim','East Sikkim','Karthok','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737132,'Sikkim','East Sikkim','Kateng Bokrang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737134,'Sikkim','East Sikkim','Khamdong','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737134,'Sikkim','East Sikkim','Kokalay','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737102,'Sikkim','East Sikkim','Kyanglasha','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737131,'Sikkim','East Sikkim','Latuk','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737103,'Sikkim','East Sikkim','Lingdok','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737102,'Sikkim','East Sikkim','Lingdum','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737134,'Sikkim','East Sikkim','Lingee','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737134,'Sikkim','East Sikkim','Lingmoo','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737131,'Sikkim','East Sikkim','Lingtam','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737134,'Sikkim','East Sikkim','Lingzey','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737106,'Sikkim','East Sikkim','Linkey','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737103,'Sikkim','East Sikkim','Luing','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737107,'Sikkim','East Sikkim','Lumlingthyang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737134,'Sikkim','East Sikkim','Lunsing','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737135,'Sikkim','East Sikkim','Majitar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737138,'Sikkim','East Sikkim','Makha','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737132,'Sikkim','East Sikkim','Mamring','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737132,'Sikkim','East Sikkim','Maney Dara','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737135,'Sikkim','East Sikkim','Middle Camp','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737106,'Sikkim','East Sikkim','Namcheybong','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737134,'Sikkim','East Sikkim','Namphing','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737132,'Sikkim','East Sikkim','Namthang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737135,'Sikkim','East Sikkim','Nandok','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737134,'Sikkim','East Sikkim','Nazitam','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737134,'Sikkim','East Sikkim','Neya','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737131,'Sikkim','East Sikkim','North Regu','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737102,'Sikkim','East Sikkim','Pabyiok','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737106,'Sikkim','East Sikkim','Pacheykhani','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737106,'Sikkim','East Sikkim','Pakyong','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737131,'Sikkim','East Sikkim','Parkha','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737103,'Sikkim','East Sikkim','Penlong','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737131,'Sikkim','East Sikkim','Phadamchen','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737103,'Sikkim','East Sikkim','Rajbhawan','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737107,'Sikkim','East Sikkim','Rakdong','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737107,'Sikkim','East Sikkim','Raley Khesey','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737131,'Sikkim','East Sikkim','Rangli Bazar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737132,'Sikkim','East Sikkim','Rangpo','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737135,'Sikkim','East Sikkim','Ranipool','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737135,'Sikkim','East Sikkim','Rautey-rumtek','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737135,'Sikkim','East Sikkim','Ray-mindu','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737133,'Sikkim','East Sikkim','Rhenock','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737131,'Sikkim','East Sikkim','Rolep','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737133,'Sikkim','East Sikkim','Rorathang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737135,'Sikkim','East Sikkim','Rumtek','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737134,'Sikkim','East Sikkim','Sakhu Busty','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737107,'Sikkim','East Sikkim','Samdong','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737102,'Sikkim','East Sikkim','Samdur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737135,'Sikkim','East Sikkim','Samlick-marchak','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737134,'Sikkim','East Sikkim','Sangkhola','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737102,'Sikkim','East Sikkim','Sherathang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737133,'Sikkim','East Sikkim','Shivalaya Mandir lingsey','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737101,'Sikkim','East Sikkim','Sichey Gaon','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737134,'Sikkim','East Sikkim','Sinchuthang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737134,'Sikkim','East Sikkim','Singtam','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737134,'Sikkim','East Sikkim','Song','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737131,'Sikkim','East Sikkim','South Regu','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737133,'Sikkim','East Sikkim','Sudunglakha','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737134,'Sikkim','East Sikkim','Sumin','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737102,'Sikkim','East Sikkim','Tadong','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737134,'Sikkim','East Sikkim','Tarku','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737103,'Sikkim','East Sikkim','Tashiling','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737133,'Sikkim','East Sikkim','Taza','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737134,'Sikkim','East Sikkim','Temi Tarku','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737106,'Sikkim','East Sikkim','Tshalamthang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737134,'Sikkim','East Sikkim','Tumin','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737132,'Sikkim','East Sikkim','Turung','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737133,'Sikkim','East Sikkim','Upper Dalapchand','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737133,'Sikkim','East Sikkim','Upper Khamdong','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737135,'Sikkim','East Sikkim','Upper Martam','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737132,'Sikkim','East Sikkim','Upper Pendam','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737134,'Sikkim','East Sikkim','West Pendam','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737134,'Sikkim','East Sikkim','Yangyang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737120,'Sikkim','North Sikkim','Chungthang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737117,'Sikkim','North Sikkim','Kabi','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737120,'Sikkim','North Sikkim','Lachen','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737120,'Sikkim','North Sikkim','Lachung','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737116,'Sikkim','North Sikkim','Lingthem','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737116,'Sikkim','North Sikkim','Lower Dzongu','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737116,'Sikkim','North Sikkim','Mangan','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737116,'Sikkim','North Sikkim','Manul','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737116,'Sikkim','North Sikkim','Men Rong rong','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737120,'Sikkim','North Sikkim','Naga','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737116,'Sikkim','North Sikkim','Namok','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737116,'Sikkim','North Sikkim','Phamtam','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737118,'Sikkim','North Sikkim','Phensong','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737119,'Sikkim','North Sikkim','Phudong','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737116,'Sikkim','North Sikkim','Ramthang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737116,'Sikkim','North Sikkim','Rangrang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737116,'Sikkim','North Sikkim','Sangkalan','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737120,'Sikkim','North Sikkim','Shipgyare','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737116,'Sikkim','North Sikkim','Singhik','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737116,'Sikkim','North Sikkim','Tingchim','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737116,'Sikkim','North Sikkim','Tingvong','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737126,'Sikkim','South Sikkim','Assangthang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737139,'Sikkim','South Sikkim','Barfung','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737139,'Sikkim','South Sikkim','Ben','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737139,'Sikkim','South Sikkim','Berang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737126,'Sikkim','South Sikkim','Damthang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737128,'Sikkim','South Sikkim','Kerabari','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737139,'Sikkim','South Sikkim','Kewzing','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737126,'Sikkim','South Sikkim','Kitam','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737102,'Sikkim','South Sikkim','Kupup','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737128,'Sikkim','South Sikkim','Lungchuk','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737126,'Sikkim','South Sikkim','Maniram','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737128,'Sikkim','South Sikkim','Manpur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737128,'Sikkim','South Sikkim','Melli Bazar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737128,'Sikkim','South Sikkim','Melli Dara','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737126,'Sikkim','South Sikkim','Mic Khola','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737126,'Sikkim','South Sikkim','Namchi','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737126,'Sikkim','South Sikkim','Nandugaon','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737121,'Sikkim','South Sikkim','Okharey','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737126,'Sikkim','South Sikkim','Pabong','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737128,'Sikkim','South Sikkim','Payiong','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737126,'Sikkim','South Sikkim','Perbing','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737126,'Sikkim','South Sikkim','Phalidara','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737139,'Sikkim','South Sikkim','Phamtam','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737121,'Sikkim','South Sikkim','Pipalay','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737126,'Sikkim','South Sikkim','Poklok','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737139,'Sikkim','South Sikkim','Ralang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737128,'Sikkim','South Sikkim','Rateypani','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737139,'Sikkim','South Sikkim','Ravangla','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737121,'Sikkim','South Sikkim','Reshi','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737121,'Sikkim','South Sikkim','Ribdi-bhareng','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737126,'Sikkim','South Sikkim','Rong','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737128,'Sikkim','South Sikkim','Sadam','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737121,'Sikkim','South Sikkim','Sanchabarey Daramdim','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737121,'Sikkim','South Sikkim','Sanganath','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737139,'Sikkim','South Sikkim','Sangmoo','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737126,'Sikkim','South Sikkim','Shalghari','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737126,'Sikkim','South Sikkim','Singhithang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737121,'Sikkim','South Sikkim','Sombaria','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737121,'Sikkim','South Sikkim','Soreng','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737126,'Sikkim','South Sikkim','Sorok','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737128,'Sikkim','South Sikkim','Sumbuk','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737139,'Sikkim','South Sikkim','Tingmoo','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737139,'Sikkim','South Sikkim','Tinkitam','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737128,'Sikkim','South Sikkim','Turuk','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737126,'Sikkim','South Sikkim','Wok','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737111,'Sikkim','West Sikkim','Arithang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737121,'Sikkim','West Sikkim','Arubotay','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737111,'Sikkim','West Sikkim','Bhaluthang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737121,'Sikkim','West Sikkim','Budang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737121,'Sikkim','West Sikkim','Buriakhop','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737121,'Sikkim','West Sikkim','Chakung','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737111,'Sikkim','West Sikkim','Chingthang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737121,'Sikkim','West Sikkim','Chumbong','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737113,'Sikkim','West Sikkim','Darap','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737113,'Sikkim','West Sikkim','Dentam','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737111,'Sikkim','West Sikkim','Gayzing','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737111,'Sikkim','West Sikkim','Gerathang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737113,'Sikkim','West Sikkim','Hee Gaon','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737113,'Sikkim','West Sikkim','Kaluk','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737111,'Sikkim','West Sikkim','Karjee','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737113,'Sikkim','West Sikkim','Karmatar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737113,'Sikkim','West Sikkim','Khechuperi','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737111,'Sikkim','West Sikkim','Legship','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737111,'Sikkim','West Sikkim','Lingchom','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737121,'Sikkim','West Sikkim','Majitar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737121,'Sikkim','West Sikkim','Malbasey','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737113,'Sikkim','West Sikkim','Mechi Aching','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737113,'Sikkim','West Sikkim','Namphu','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737121,'Sikkim','West Sikkim','Naya Bazar','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737113,'Sikkim','West Sikkim','Pelling','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737113,'Sikkim','West Sikkim','Radhu Khandu','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737111,'Sikkim','West Sikkim','Rangship','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737113,'Sikkim','West Sikkim','Rimbi','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737111,'Sikkim','West Sikkim','Rinchenpong','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737111,'Sikkim','West Sikkim','Sinek','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737121,'Sikkim','West Sikkim','Sri Badam','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737121,'Sikkim','West Sikkim','Suldung','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737121,'Sikkim','West Sikkim','Takuthang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737111,'Sikkim','West Sikkim','Tashiding','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737121,'Sikkim','West Sikkim','Tharpu','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737113,'Sikkim','West Sikkim','Thingling','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737121,'Sikkim','West Sikkim','Tikpur','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737121,'Sikkim','West Sikkim','Timburbong','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737113,'Sikkim','West Sikkim','Uttarey','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737111,'Sikkim','West Sikkim','Yangtey','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737111,'Sikkim','West Sikkim','Yangthang','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737113,'Sikkim','West Sikkim','Yuksom','cc_in');
insert into postal_code(postal_code_id,postal_cd,state_name,district_name,office_name,country_cd) values (null,737121,'Sikkim','West Sikkim','Zoom','cc_in');
